### ISSUE TITLE
Since when are  3-point palettes banned from BC2 and BC3?

### ISSUE THREAD

**Issue by fynv** [Microsoft/DirectXTex#101]
In BC.cpp, I see the code:
XMVECTOR clr2, clr3;
if (isbc1 && (pBC->rgb[0] <= pBC->rgb[1]))
{
clr2 = XMVectorLerp(clr0, clr1, 0.5f);
clr3 = XMVectorZero(); // Alpha of 0
}
else
{
clr2 = XMVectorLerp(clr0, clr1, 1.f / 3.f);
clr3 = XMVectorLerp(clr0, clr1, 2.f / 3.f);
}
The "isbc1" flag here indicates that for BC2 and BC3, here we are always using a 4-point palette.
From quality's aspects, we can sometimes yield better PSNR using a 3-point palette even for opaque blocks.
I noticed that some older version of DirectXTex (that comes with DX SDK) actually behaves differently with this. Since when have we been using the isbc1 flag? Is this behavior clarified in any document?
Thanks.

**Comment by fynv** [comment]
Just looked at D3D10FunctionalSpec. Seems there's no other choice.. Closing.

**Comment by walbourn** [comment]
This feature of BC1 dates back to the original [DXT1](https://en.wikipedia.org/wiki/S3_Texture_Compression#DXT1) compression scheme by S3. Per the original spec, DXT2/DXT3/DXT4/DX5 always use the 4-color behavior of DXT1 regardless of the color order.
