### ISSUE TITLE
[Question] How to put texconv output file into their original location?

### ISSUE THREAD

**Issue by admiralmikan** [Microsoft/DirectXTex#104]
I need help with texconv command. Whenever I perform texconv.exe -m 1 -y -r *_AM.dds to delete mip maps on my .DDS files, the output file will be put on where my texconv is located. Do you know extra command that will forced texconv to put output file into their original location, thus replace their original files, too? Since I use -r command that will search for subfolders too.

Thank you very much!

![2018-06-11 08_54_52-british - copy edit](https://user-images.githubusercontent.com/17843605/41210091-a83f30a0-6d59-11e8-89f8-9c23be786f85.jpg)

**Comment by walbourn** [comment]
The ``texconv`` tool outputs to either the 'current working directory' or to the path specified by the `-o-` parameter. See the [wiki](https://github.com/Microsoft/DirectXTex/wiki/Texconv).

**Comment by SearcherNo81** [comment]
For anyone having trouble getting -o to work: Using a quoted output path with a trailing backslash will result in incorrectly placed files. The backslash will be read as an escape character for the quote and the output path will be ignored. -o "C:\path\\" will not work, but -o "C:\path" will.

**Comment by walbourn** [comment]
Note that the tools also support 'linux' style path separators, and you can use `--` by itself to disable command-switch processing so you can start a path with a `/`. That doesn't necessarily help with the `-o` case since that's a switch, but it can be used for input file lists.
