### ISSUE TITLE
BC1 compression artefacts

### ISSUE THREAD

**Issue by comeradealexi** [Microsoft/DirectXTex#110]
Hi,

We're finding that converting textures with the BC1 format is resulting in colour artefacts in the final image which are quite obvious in our game when the texture is large and stretched.

A zoomed in section of our source image looks like this:
![image](https://user-images.githubusercontent.com/7004344/42747109-d2070018-88d2-11e8-8e2f-f544cfc41e22.png)

The result of BC1 compression looks like this:

Notice the purple and green colour tints which have been added.
![image](https://user-images.githubusercontent.com/7004344/42747100-cb586946-88d2-11e8-83dc-76d6c3cec0c5.png)

We've tried using -bcuniform and -bcdither but these still resulted in colour problems in the final image.

Attached is the source TGA we are using:
[WindowTexture.zip](https://github.com/Microsoft/DirectXTex/files/2196785/WindowTexture.zip)

Any help/assistance would be greatly appreciated.

Alex

**Comment by walbourn** [comment]
Classic DXTn block compression is going to have difficulty with smooth black & white gradients as it's just the nature of the way the compression works (a single color segment with two R5G6B5 end-points has to closest-match all four pixels in a block). As such, that particular image is probably not a great fit.

In fact, why not just use ``DXGI_FORMAT_R8_UNORM`` to store it as monochrome image that is already much smaller than the original R8G8B8A8 version but without the artifacts of block compression? You will need to handle replicating the channel data in the shader but it's easy and cheap to do.

Another option for monochrome data is to use ``BC4_UNORM``  which is supported on all Direct3D Hardware Feature Level 10.0 or better cards, although I suspect for the smooth gradient you'd be better off sticking with ``R8_UNORM``.

**Comment by comeradealexi** [comment]
Thank you for the detailed reply @walbourn!
