### ISSUE TITLE
Resize fails on a 16k x 16k R8G8B8A8_SNORM texture

### ISSUE THREAD

**Issue by stonelance** [Microsoft/DirectXTex#111]
It looks like it hits PerformResizeViaF32 which converts the texture to a R32G32B32A32_FLOAT float texture, and then calls PerformResizeUsingWIC which fails because the slicePitch passed to CreateBitmapFromMemory ends up as 0 once casted to a UINT.

Example call where bigImage is 16384 by 16384 and DXGI_FORMAT_R8G8B8A8_SNORM:
DirectX::Resize(bigImage.GetImage(0, 0, 0), 128, 128, DirectX::TEX_FILTER_FANT | DirectX::TEX_FILTER_SEPARATE_ALPHA, smallImage);

**Comment by stonelance** [comment]
I should mention I'm not sure how old the version of DirectXTex that I'm using is, although a quick look over the current code and it doesn't look any different in a way that might fix this bug.

I also tried using TEX_FILTER_FORCE_NON_WIC as a work around, but it appears ResizeBoxFilter can only resize to a size that is half of the original size.

**Comment by walbourn** [comment]
Is your application 32-bit or an x64 native one? I've found that really large textures fail processing in 32-bit apps due to out-of-memory conditionss

**Comment by stonelance** [comment]
64bit.  It isn't a OOM issue.  The problem is at some point in the resize code it is trying to cast the 64 bit size_t of the image 0x100000000 to a 32 bit UINT to pass it to WIC, and it results in a size of 0, and WIC returned E_INVALIDARG.  I was able to work around it by using the TEX_FILTER_FORCE_NON_WIC code path to generate a mip chain, and then pull out the mip I needed from there.

**Comment by walbourn** [comment]
I see, so at a minimum I need some arithmetic overflow guards for the ``slicePitch`` in the WIC paths. For most of the DXGI formats that WIC supports, 16384 x 16384 fits in a 32-bit ``UINT``, but not the formats that have to go through the F32 path.

You can try doing repeated NON_WIC resizes by half to hit your 128 size, or even just use ``GenerateMips`` then peel off the 128 sized level. Other you could try using linear/cubic filtering.

**Comment by walbourn** [comment]
In theory I can create a special case here that uses 96bpp float32 for RGB and another float32 for the alpha that would fit in the limits of WIC. Not looking forward to it, but it's probably the only robust solution...

**Comment by walbourn** [comment]
Another option might be to use float16 in cases where it's too big...

Can you share your 16384 x 16384 image for development and testing?

**Comment by walbourn** [comment]
My proposed robust fix is [here](https://github.com/Microsoft/DirectXTex/pull/112), although I need more test assets to actually ensure coverage before I accept the changes.

**Comment by walbourn** [comment]
With the fix, you should be good to go with 16kt textures in the x64 native configuration, but for your particular case it's going to use custom filtering.

As such, you don't want to force "FANT" unless you are only half-sizing. If you use the default or explicitly pick LINEAR, CUBIC, or TRIANGLE it should work.
