### ISSUE TITLE
Mipmaps alter colors if removed and added again

### ISSUE THREAD

**Issue by cisi80** [Microsoft/DirectXTex#114]
Hi,

when using this command to remove mipmaps:
texconv -gpu 1 -f BC3_UNORM -m 1 -nologo -o "'.$path_dir.'" -y "'.$singlefiles[$i].'"'
(resulting image is still correct!)
![orig_nomips](https://user-images.githubusercontent.com/42414552/44157332-630f5a80-a0dc-11e8-9517-455a080c8cdb.jpg)

and than to add them again:
texconv -gpu 1 -f BC3_UNORM -m 0 -nologo -o "'.$path_dir.'" -y "'.$singlefiles[$i].'"'
![addedmips](https://user-images.githubusercontent.com/42414552/44157331-630f5a80-a0dc-11e8-90c6-8801812dc8f4.jpg)

the resulting image colors (i only worked on the grass textures in the given example!) are not the same as the original ones. They seem lighted up as if they where a lot brighter.
The bug also affects BC7 or BC1 or R8G8B8A8 the same way so i think its related to the mipmaps generation process itself somehow.

I noticed it when batch resizing images for the game skyrim SE,
Finally after a lot of testing i found out it is the process of adding mipmaps to an image witohout mipmaps 

after resizing that messes up the colors.

regards,

**Comment by walbourn** [comment]
Did you end up resolving the issue? What was it?
