### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/DirectXTex#115]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “ScratchImage::Release”](https://github.com/Microsoft/DirectXTex/blob/114a0acf6bf1ff895ba123564d030b15b00670b5/DirectXTex/DirectXTexImage.cpp#L680 "Update candidate: ScratchImage::Release()").

**Comment by walbourn** [comment]
It is true that you don't need to guard calls to ``delete`` or ``delete[]`` against nullptr, and I'm aware of that. That said, I am using in that particular place a long-standing practice of 'safe release' where I ensure the pointer is set to null if it wasn't after freeing it:

    #ifndef SAFE_DELETE
    #define SAFE_DELETE(p)       { if (p) { delete (p);     (p) = nullptr; } }  
    #endif

In general I favor the Modern C++ practice of using smart-pointers, but for the case of ``ScratchImage`` which itself is basically a memory container I stuck with the older design.

**Comment by elfring** [comment]
How do you think about to increase the usage of smart pointers also for this software instead?
