### ISSUE TITLE
GetDXGIFormat() fails to identify the format of some valid BC1 DDS files

### ISSUE THREAD

**Issue by jshofmann** [Microsoft/DirectXTex#116]
I've run into a problem with DirectXTex failing to identify the format of some valid DDS files. These are BC1-encoded files with punchthrough alpha, produced probably around 10 years ago by unknown tools. Their DDS_PIXELFORMAT::dwFlags are set to DDPF_FOURCC | DDPF_ALPHAPIXELS (0x00000005). The presence of that DDPF_ALPHAPIXELS flag is causing the "if (ddpfFlags == entry->ddpf.flags)" test at line 169 of DirectXTexDDS.cpp to fail for those files, so GetDXGIFormat() is returning DXGI_FORMAT_UNKNOWN instead of DXGI_FORMAT_BC1_UNORM as expected. I've been able to fix this problem in a manner similar to the handling of NVTT textures in GetDXGIFormat(), by replacing line 169 of DirectXTexDDS.cpp with this:

            // DDPF_ALPHAPIXELS is set by some encoders, remove that flag from consideration
            if ((ddpfFlags & ~DDS_ALPHAPIXELS) == entry->ddpf.dwFlags)

If you want, I can send you a sample DDS file that has this flag set. Note also, the engine project I run uses a DDPF_SRGB flag similar to what the NVIDIA encoder has used, do we need that flag test (line 169) at all?  It seems awfully restrictive, perhaps line 156 should mask off only the range of Microsoft-defined DDPF flags? (i.e. line 156 would read "uint32_t ddpfFlags = ddpf.flags & 0x000FFFFF", and then the test for NVTT textures would be unnecessary.) Of course, the above fix will still be necessary in that case.

(The reason we don't use a DDS_HEADER_DXT10 structure is that the presence of that structure breaks an awful lot of DDS tools...yes, those tools should be updated, but "it's the tool vendor's fault!" is not an argument that sits well with my art staff now denied use of their favorite tools and workflow.)

Thanks for producing a wonderfully useful library!

**Comment by walbourn** [comment]
Please provide an example ``DDS`` so I can take a look...

**Comment by jshofmann** [comment]
Here is one, zipped because GitHub refuses to attach a file with a .dds extension.
[ui_Button_DPAD_0.zip](https://github.com/Microsoft/DirectXTex/files/2298516/ui_Button_DPAD_0.zip)

**Comment by jshofmann** [comment]
Just realized I can merge the two fixes into one statement, at line 156:

        uint32_t ddpfFlags = ddpf.flags & 0x000FFFFE;

This masks off both DDPF_ALPHAPIXELS and any potential use of the high-order flag bits by vendor tools, testing only the DDPF flags defined by the DDS standard (with the exception of DDPF_ALPHAPIXELS, of course.)

**Comment by walbourn** [comment]
Are you hitting this failure with ``DDSTextureLoader`` or DirectXTex ``LoadDDSFromFile``?

**Comment by walbourn** [comment]
I see, this is specifically a NVTT file, so I'm already using non-standard DDS behavior here...

**Comment by walbourn** [comment]
Here's what [ddsdump]() finds:

    DDS d:ui_Button_DPAD_0.dds
    Flags 000a1007: CAPS HEIGHT WIDTH PIXELFORMAT MIPMAPCOUNT LINEARSIZE
    64 x 64
    Linear Size: 2048
    Mipmap count: 1
    Surface flags: 00401008: COMPLEX TEXTURE MIPMAP
    PIXELFORMAT: 00000005: ALPHAPIXELS FOURCC
    FourCC = 827611204 'DXT1'
    DXGI_FORMAT_BC1_UNORM

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/Microsoft/DirectXTex/commit/43969ca15f4e46d8338c669e2ed1d5d953206724)
