### ISSUE TITLE
[Question] use spaces or cyrilic chars in filepath

### ISSUE THREAD

**Issue by Tosyk** [Microsoft/DirectXTex#118]
Whenever I try to use this command:
`C:\Program Files\tools>texconv.exe -y -f R8G8B8A8_UNORM -ft tga -o "D:\bra elite\" "D:\bra elite\bra_elite_n.dds"`
or
`C:\Program Files\tools>texconv.exe -y -f R8G8B8A8_UNORM -ft tga -o "D:\бра элит\" "D:\бра элит\bra_elite_n.dds"`

I get error:
`reading elite\cn_e3_14_bra_elite_bag_n.dds FAILED (80070003)`

I'm using it with drag&drop on CMD:
`"C:\Program Files\tools\texconv.exe" -y -f R8G8B8A8_UNORM -ft tga -o "%~dp1" "%~1"`

**Comment by walbourn** [comment]
``80070003`` is the HRESULT for "ERROR_PATH_NOT_FOUND". It could be a localization issue, but I use all wchar Unicode strings so that should work.

**Comment by walbourn** [comment]
Ah, I see it. You accidentally 'escaped' the quote with the ``\"`` 

    -o "D:\бра элит\" "D:\бра элит\bra_elite_n.dds"

Needs to be

    -o "D:\бра элит\\" "D:\бра элит\bra_elite_n.dds"
