### ISSUE TITLE
Converting to D3DFMT_V8U8 with DirectXTex, is it possible?

### ISSUE THREAD

**Issue by jonwil** [Microsoft/DirectXTex#119]
We have some old Direct3D9 code that uses D3DXCreateTextureFromFileInMemoryEx from d3dx9 to read a dds file (in DXT5 format although it would be nice if we could use A8R8G8B8 DDS files or .tga files as input as well) into memory and convert it to D3DFMT_V8U8 at the same time. We are now wanting to port that code to D3D11.

Is there a way to use DirectXTex to read input data (in DXT5, A8R8G8B8 or otherwise) and get out the same D3DFMT_U8V8 data that D3DX9 would give us?

**Comment by walbourn** [comment]
In DirectXTex and in DirectX Tool Kit's ``DDSTextureLoader`` and ``ScreenGrab`` modules, I treat legacy Direct3D 9 era ``DDS`` files with ``D3DFMT_V8U8`` as equivalent to the format ``DXGI_FORMAT_R8G8_SNORM``. You can convert to/from that format with DirectXTex.
