### ISSUE TITLE
Does directxtex support D2D1?how to save bitmap from ID2D1HwndRenderTarget?

### ISSUE THREAD

**Issue by evehal** [Microsoft/DirectXTex#122]
i wanna save bitmap from ID2D1HwndRenderTarget in kinect v2 bodybasics demo
thanks for help

**Comment by walbourn** [comment]
DirectXTex and the rest of my libraries are focused on Direct3D scenarios. Direct2D supports WIC directly, so that's probably the most direct solution. See [StackOverflow](https://stackoverflow.com/questions/14536610/how-to-save-bitmap-to-file-using-direct2d-and-id2d1hwndrendertarget).
