### ISSUE TITLE
Support Custom NVTT flags ?

### ISSUE THREAD

**Issue by Paliha** [microsoft/DirectXTex#125]
nvidia-texture-tools

```
enum DDPF        
         // Custom NVTT flags.
          DDPF_NORMAL = 0x80000000U,
          DDPF_SRGB = 0x40000000U,
```

DirectXTex

```
if ((hdr.reserved1[9] == MAKEFOURCC('N', 'V', 'T', 'T'))
            && (ddpf.flags & 0x40000000 /* DDPF_SRGB */))
        {
            format = MakeSRGB(format);
        }
```

analogue BC5_UNORM, but the output is dominated by the Green and Red channel, and there is no blue channel

**Comment by walbourn** [comment]
Can you provide an example ``DDS` file that demonstrates your concern?

There's nothing here in particular that indicates a BC5 format.

**Comment by walbourn** [comment]
For normal maps I think the only real behavior I can implement here is some special case for conversion that reconstructs the 'missing channel' for normal maps encoded as BC5. That's probably going to be a feature I'd make optional rather than try to plug through this NVIDIA-only "metadata".

**Comment by walbourn** [comment]
Note that the 'reconstruct' option is also proposed [here](https://github.com/Microsoft/DirectXTex/issues/53)
