### ISSUE TITLE
Invalid value specified with -w (256)

### ISSUE THREAD

**Issue by cyberconan** [Microsoft/DirectXTex#128]
Hi! When I'm using August 17, 2018 texconv.exe release, I get "Invalid value specified with -w (256)" error when I use this command line:
texconv.exe -nologo -if TRIANGLE -w 256 -h 256 -y -f BC7_UNORM -ft DDS
The problem was no present in April 23, 2018 release.
Kind regards!

**Comment by walbourn** [comment]
What toolset and project did you use to build the tool? Are you using x86 or x64 / Debug or Release?

**Comment by walbourn** [comment]
I just tried that release and it worked fine for me with that command line. The main reason you'd get that error would be if ``swscanf_s`` returned something other than 1.

What versions of Visual Studio do you have installed on your system?

**Comment by cyberconan** [comment]
I think my scenario is not typical, I'm using the compiled textconv.exe August version under Wine 4.0-rc4.

**Comment by walbourn** [comment]
Ah, well, then that's likely the issue. VS 2015 and VS 2017 use the [Universal CRT](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/) to implement functions like the ``stdio.h`` functions I'm using here. That's a bug for the Wine folks.

**Comment by cstrahan** [comment]
@cyberconan Did you ever file this as an issue with the Wine developers?
