### ISSUE TITLE
Mipmaps as input other than generating automatically

### ISSUE THREAD

**Issue by nhy002** [Microsoft/DirectXTex#131]
about texconv command tool
Can I use mipmaps generated by myself as input? I may apply "alpha to coverage" to my mipmaps or generate mipmaps from some other filtering methods. If not, can I get from later version?

**Comment by walbourn** [comment]
You can write your own tools using DirectXTex and do whatever you want. I don't have an existing sample tool that provides custom mips.

Note, I just accepted a [PR](https://github.com/Microsoft/DirectXTex/pull/82) that added alpha coverage to texconv.
