### ISSUE TITLE
Cannot link texconv in release mode

### ISSUE THREAD

**Issue by jeffrson** [Microsoft/DirectXTex#132]
I cannot link texconv in release mode.

I compile and link DirectXTex in release mode, but the reference texconv uses points to the debug lib?!

Error message is
LINK : fatal error LNK1181: cannot open input file '<...>\DirectXTex\DirectXTex\Bin\Desktop_2017\Win32\Debug\DirectXTex.lib'

When I compile a debug mode DirectXTex.lib, I get lots of specific linker errors.

Visual Studio 15.9.9 on Windows 10

**Comment by walbourn** [comment]
I'm unable to reproduce this. I do a full clean (``rd /s /q DirectXTex\bin``), opened up ``DirectXTex_Desktop_2017.sln``, selected "Release/Win32" and did a build. It build fine.
