### ISSUE TITLE
Targas and sRGB color correctness.

### ISSUE THREAD

**Issue by davisongeorge** [microsoft/DirectXTex#136]
I have been having trouble with a LUT getting values mangled by texassemble and tracked it down to targas being assumed to be linear, then getting converted to sRGB

I was wondering what the logic behind assuming targa files are linear on load was. I believe that they are always assumed to be in sRGB space by every other program in a typical tools chain. There does not appear to be a way to override this behavior outside of rewriting it in each tool, which I have.

Another option is doing this through texconv, with a very counterintuitive set of options and another pass that looses even more precision in your textures, or treat them as unorm and fix later in the pipe. I feel like there is some collection of color correction errors here that are canceling themselves out in a way that makes all of this quite unpredictable without some deep code diving.

**Comment by walbourn** [comment]
Generally for the DirectXTex readers, the formats don't have a way to indicate colorspace, so I use the more conservative approach used by the legacy D3DX9 library of not assuming one way or the other and returning the 'generic' DXGI format. Using sRGB metadata from WIC lets me handle it a bit better for formats like PNG.

Another issue is that ``DXGI_FORMAT_B5G5R5A1_UNORM`` does not have an ``_SRGB`` equivalent defined for DXGI, so only a 24bpp or 32bpp would be able to use an explicit ``_SRGB`` format. I can certainly look at adding a flag to the TGA loader code to support this scenario for 24bpp/32bpp, but it wouldn't really help 16bpp.

There's also the general problem that ``DDS`` files don't contain an explicit colorspace in most cases. Again, only a small subset of DXGI formats have ``_SRGB`` equivalents. 

The purpose of the ``-srgbi`` and ``-srgbo`` switches is to let you control that conversion when needed.

**Comment by davisongeorge** [comment]
I understand that. But in this case the default behavior is squashing real
data and either posterizing it or changing the curve depending on the
output format, with no warning. My complaint was more that this issue is
hidden from people who are using the command line tools alone.

In our case I changed the default behavior to NEVER apply a color
correction to targa files. Just treat them in the gamma space of the
desired output format. This makes both our legacy code and our gamma
correct pipeline work without additional options, and simplifies texconv as
well. This might work in the general case for everyone, but i'd have to
think about what other packing options people might be using for their
material pipelines.

**Comment by walbourn** [comment]
I wonder if a general ``-nocolorspaceconversion`` would work. That said, basically everything in WIC does SRGB stuff when moving from unorm to floating-point/fixed anyhow so it's a bit tricky.

**Comment by walbourn** [comment]
There is an extension area for TGA 2.0 that encodes SRGB (``22 / 10``) instead of linear, but it's not widely used. Can you check to see if your ``TGA`` files in your pipeline write this? You can use [tgadump.cpp](https://raw.githubusercontent.com/wiki/Microsoft/DirectXTex/tgadump.cpp).

**Comment by walbourn** [comment]
See this [PR](https://github.com/microsoft/DirectXTex/pull/199/files) as well
