### ISSUE TITLE
Unbound from DirectX and compile on platforms other than Windows

### ISSUE THREAD

**Issue by Xottab-DUTY** [microsoft/DirectXTex#141]
I don't see that anyone has suggested it. Really, why not? This is a good library that can be used for managing DDS textures only and DirectX integration can be made optional.

**It has best support for DDS format**, while other libs has bugs (like [this](https://github.com/g-truc/gli/issues/167) one) or support the format partially. (like FreeImage, which can only read DDS, but not save)

**Comment by walbourn** [comment]
While some of the library could be considered distinct from the "DirectX" APIs, it makes heavy use of Windows Imaging Component which is only on Microsoft platforms. As such, really only a small subset of the library could be made to build for non-Microsoft platforms.

I do have a CMake file for it and update conformance for clang/LLVM, so it should be easy to cut & paste the code into something or create a fork for your needs.
