### ISSUE TITLE
SaveToEXRFile no save mipmap data?

### ISSUE THREAD

**Issue by pannan** [microsoft/DirectXTex#143]
The first parameter of SaveToEXRFile is Image instead of ScratchImage. This way you can't save mipmap data?

**Comment by walbourn** [comment]
Most of the image formats can only save a single image. You can save 'multiframe' images to TIFF and GIF, but they may or may not support each frame image being a distinct size. As such, I only really expect mips to be written to ``DDS`` files.

You can write each mip as an individual file by using ``ScratchImage::GetImage``.

**Comment by pannan** [comment]
DDS is a good choice.
Thanks for your reply.
