### ISSUE TITLE
is it possible to add min/max filter to GenerateMipMaps?

### ISSUE THREAD

**Issue by dong-zhan** [microsoft/DirectXTex#144]
as title, thanks

**Comment by walbourn** [comment]
Did your solve your issue?

**Comment by dong-zhan** [comment]
No, I have not.
I was planning to make min/max depth map mipmaps for SSR (screen space reflection)
Then I realize, this min/max operation is pretty common, it provides a structure a hierarchy, so, I was kind of hoping you can provide this function.


Sent from Mail for Windows 10

**Comment by dong-zhan** [comment]
I solved this with compute shader, could you please close this issue? thanks!
