### ISSUE TITLE
How to convert dds volume texture into multiple pngs?

### ISSUE THREAD

**Issue by fatboyzz** [microsoft/DirectXTex#145]
I can create volume texture with

texassemble.exe volume a.png b.png -o c.dds

How can I convert c.dds back into a.png and b.png.

**Comment by walbourn** [comment]
[texdiag](https://github.com/microsoft/DirectXTex/wiki/texdiag) has the ability to dump all the surfaces out of ``DDS``.

```
texdiag ddsdump c.dds
```
