### ISSUE TITLE
Texconv, error when converting BC5 to .png

### ISSUE THREAD

**Issue by dsnyder-bsi** [microsoft/DirectXTex#146]
After converting a 3-channel .png to a BC5 .dds using Texconv, i tried converting the .dds back to a .png from a command line.  i get the following error message "FAILED (80070032)".  Doing an internet search for that error number doesn't help me much.  

However, I am able to convert the BC5 .dds to .png using Visual Studio.  The BC5 .dds file looks good in Visual Studio. 

I've tried all sorts of command line options, including the following simple command line, but no luck:
    texconv -ft png XXX.dds

I have attached a .zip of a BC5 .dds that is not working for me.
[Helmet_CbCr_Mip1_BC5.zip](https://github.com/microsoft/DirectXTex/files/3469217/Helmet_CbCr_Mip1_BC5.zip)

Does anyone have a clue what is going wrong, here?

Thanks,
Doug

**Comment by walbourn** [comment]
The error is an HRESULT which translates to ``ERROR_NOT_SUPPORTED``.

Basically, you can't write BC5 format to a ``.png``. What you need to do is provide a target pixel format that is supported by ``png``:

    texconv -ft png -f rgba XXX.dds

See the [wiki](https://github.com/microsoft/DirectXTex/wiki/Texconv).

**Comment by dsnyder-bsi** [comment]
Is this just a shortcoming of Texconv?  Visual Studio can convert BC5 to
.png, so it doesn't seem to be a fundamental problem with BC5, PNG or DDS.
a 2-plane BC5 can be combined with a 0-filled plane and then written to a
3-plane PNG.  This appears to be what Visual Studio is doing.

Shouldn't this functionality be added to Texconv as a way to visual a BC5
encoding?

are there formats other than PNG that Texconv supports for exporting from
BC5?

doug

**Comment by walbourn** [comment]
Visual Studio is actually using DirectXTex so will produce the same result.

This is mostly a matter of how the texconv command-line tool has historically worked from the legacy DirectX SDK. If you don't provide the ``-f`` argument, it assumes you don't want to change the target format.
