### ISSUE TITLE
license

### ISSUE THREAD

**Issue by dong-zhan** [microsoft/DirectXTex#147]
Hi,

I downloaded visual studio 2019 community version, and decided to upgrade my directX11 texture to DirectXTex, but, after I opened DirectXTex in visual studio, it gave me a notification, I need a UWP license. so, my problem is, I am not developing DirectXTex, do I need a license to use DirectXTex in my project?

**Comment by walbourn** [comment]
Which SLN did you open?

**Comment by dong-zhan** [comment]
Oh, I am sorry, I should have opened desktop, I guessed I opened windows

**Comment by dong-zhan** [comment]
thank you

**Comment by walbourn** [comment]
See the [wiki](https://github.com/microsoft/DirectXTex/wiki/DirectXTex#using-project-to-project-references)
