### ISSUE TITLE
GenerateMipMaps fails for automatic mip generation on a 1x1 texture.

### ISSUE THREAD

**Issue by The0rangeMan** [microsoft/DirectXTex#149]
HRESULT GenerateMipMaps( const Image* srcImages, size_t nimages, const TexMetadata& metadata, DWORD filter, size_t levels, ScratchImage& mipChain );

The above function fails if levels is 0 (automatic mip level detection) for a 1x1 source image. 

This is because it indirectly calls _GenerateMipMapsUsingWIC, which asserts that levels must be > 1.

I'm not sure if this is intended behavior, but it feels like a weird edge case to me, and I had to hack around it in my use of DirectXTex.

**Comment by walbourn** [comment]
What would you expect it to do if you call this function with 0 levels?

**Comment by walbourn** [comment]
It should have returned a failure:

```
    if (!_CalculateMipLevels(baseImage.width, baseImage.height, levels))
        return E_INVALIDARG;

    if (levels <= 1)
        return E_INVALIDARG;
```

**Comment by The0rangeMan** [comment]
I don't see any reason for it to fail with levels == 1. I would expect that to be a no-op personally, but returning E_INVALIDARG is definitely better than asserting.

**Comment by walbourn** [comment]
I don't see an assert in the current codebase.

**Comment by walbourn** [comment]
Since you still have ``_GenerateMipMapsUsingWIC`` in your codebase, you should look at updating to a newer version to get all the intervening bug fixes.
