### ISSUE TITLE
[Texconv.EXE] Where is the download button :D !?

### ISSUE THREAD

**Issue by Nemesis666first** [microsoft/DirectXTex#155]
Hi ;) !

Everyone is telling me "just download the texconv.exe", but I dont think this damned download button xD this makes me crazy, any idea please :p ?

**Comment by walbourn** [comment]
If you look at the [releases](https://github.com/microsoft/DirectXTex/releases), some of the have more than '2' assets... The extras are the prebuilt EXEs.

The latest one is [here](https://github.com/microsoft/DirectXTex/releases/download/oct2019/texconv.exe)

**Comment by Nemesis666first** [comment]
Indeed, thank you :D !
