### ISSUE TITLE
Desktop ARM64 support

### ISSUE THREAD

**Issue by robmikh** [microsoft/DirectXTex#156]
Hello,

I use DirectXTex as part of the [Win32CaptureSample](https://github.com/robmikh/Win32CaptureSample), and I've been able to get a build of it running on ARM64. I would make a pull request, but my change was a bit destructive since I only have Visual Studio 2019 and platform tools v142 installed. My change can be found in the [arm64desktop](https://github.com/robmikh/DirectXTex/tree/arm64desktop) branch of my fork.

Is there any interest to add ARM64 support? I'd be willing to help, I'm just not sure what's the best way to add/test it.

**Comment by walbourn** [comment]
I have ARM64 support in the UWP projects ``DirectXTex_Windows10_2017.sln``  and ``DirectXTex_Windows10_2019.sln``. Therefore I know the code builds for that platform.

ARM Win32 desktop development was highly limited, so I never had the ARM stuff in the desktop projects. I'll have to think about the best way to handle ARM64 on Win32 support for my libraries.

**Comment by walbourn** [comment]
Added to my libraries in these commits:

DirectXTex: https://github.com/microsoft/DirectXTex/commit/579a98aa1e52941891965c8e0e7185111149fe48

DirectXMesh:
https://github.com/microsoft/DirectXMesh/commit/5afe54f14c7d8919bd599feb55de04d7e723b686

DirectXTK:
https://github.com/microsoft/DirectXTK/commit/b37a5afa1307fe719f44b271ae07b4da8edb0e12

DirectXTK12:
https://github.com/microsoft/DirectXTK12/commit/922afda35ea0c0a5587c214943451c67b8472ae5

**Comment by robmikh** [comment]
Awesome, thank you!

**Comment by robmikh** [comment]
I don't think the ARM64 lib was included in the newest package. I downloaded version 2019.12.17.1 of directxtex_desktop_win10, and the lib folder only has libs for Win32 and x64. When I try to build a project consuming the nuget package for ARM64, Visual Studio is unable to find DirectXText.lib.

**Comment by walbourn** [comment]
That's correct. I need to revisit the NuGet packages to support ARM64 desktop... I was planning to do this in the new year along with retiring VS 2015 support.

**Comment by walbourn** [comment]
The February 2020 release on NuGet includes the ARM64 desktop configurations. That said, I just got an ARM64 device so I've not had a chance yet to run through the test suits to make sure it all works :)
