### ISSUE TITLE
Maybe a mistake in wiki

### ISSUE THREAD

**Issue by ssdemajia** [microsoft/DirectXTex#160]
In DirectXTex wiki, url is https://github.com/microsoft/DirectXTex/wiki/CreateShaderResourceView
In the 'CreateShaderResourceView' Example section,
```c
if ( SUCCEEDED(hr) )
{
    ID3D11ShaderResourceView* * pSRV = nullptr;
    hr = CreateShaderResourceView( device,
        image.GetImages(), image.GetImageCount(),
        image.GetMetadata(), &pSRV );
    if ( FAILED(hr) )
    {
        ...
```
Myabe pSRV should be `ID3D11ShaderResourceView* pSRV = nullptr;`

**Comment by walbourn** [comment]
Thanks. fixed.
