### ISSUE TITLE
Miss flag(s) in the page 'Filter Flags'

### ISSUE THREAD

**Issue by pxbyt** [microsoft/DirectXTex#168]
The page 'Convert':'https://github.com/microsoft/DirectXTex/wiki/Convert' mentions that there is a flag named 'TEX_THRESHOLD_DEFAULT',
but in the page 'Filter Flags':'https://github.com/microsoft/DirectXTex/wiki/Filter-Flags', I found nothing about it.
May you please supplement them(I guess there are some other flags begin with 'TEX_THRESHOLD_')?
Thanks.

**Comment by walbourn** [comment]
Sorry if this was unclear, but the DWORD *filter* parameter points to the **Filter Flags** topic.

The float *threadhold* parameter is a different parameter and ``TEX_THRESHOLD_DEFAULT`` is simply the default value I use for that parameter.
