### ISSUE TITLE
DirectXTex converts floating point numbers to integers by different way between BC4 and BC5.

### ISSUE THREAD

**Issue by yosshin4004** [microsoft/DirectXTex#171]
DirectXTex converts floating point numbers to integers by different way between BC4 and BC5.
Is this correct behaviour?

- **In case of BC4: fractions are truncated.**

DecompressBC decodes a BC4 pixel block as float precision numbers.
_StoreScanline converts it as DXGI_FORMAT_R8_SNORM by following code.
```
	float v = XMVectorGetX(*sPtr++);
	v = std::max<float>(std::min<float>(v, 1.f), -1.f);
	*(dPtr++) = static_cast<int8_t>(v * 127.f);
```

- **In case of BC5: fractions are rounded up.**

DecompressBC decodes a BC5 pixel block as float precision numbers.
_StoreScanline converts it as DXGI_FORMAT_R8G8_SNORM by XMStoreByteN2 as follows.

```
	// Clamp to bounds
	XMVECTOR vResult = _mm_max_ps(V,g_XMNegativeOne);
	vResult = _mm_min_ps(vResult,g_XMOne);
	// Scale by multiplication
	vResult = _mm_mul_ps(vResult,g_ByteMax);
	// Convert to int by rounding
	__m128i vInt = _mm_cvtps_epi32(vResult);
```

**Comment by walbourn** [comment]
So there's no strong intention here. I generally tried to utilize DirectXMath for as many of the pixel load/store conversions as I could, and wrote the 'missing cases' directly. That said, that code dates back to 2011 so it's not always as consistent as I'd like.

I'll take a look at this when I have some time. In theory the results for the alpha portion of BC3, BC4, and BC5 should all be bit-identical given the same input.

**Comment by walbourn** [comment]
The solution here is probably to use ``lrint`` for the scalar float cases.

**Comment by walbourn** [comment]
Hmm... ``lrint`` didn't work as I'd have expected. Maybe adding 0.5f to to the truncate is sufficent.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/7823346987fc3e0c9e3b2ac4c27619d2728ca7b3)
