### ISSUE TITLE
Resize fails with large image

### ISSUE THREAD

**Issue by greg-churchillnavigation** [microsoft/DirectXTex#172]
Resize operation can fail with a large image, even after the newly added code to check for >4GB per slice.

Failure is here:
```
DirectXTexResize.cpp
	HRESULT PerformResizeUsingWIC(
		hr = pWIC->CreateBitmapFromMemory(static_cast<UINT>(srcImage.width), static_cast<UINT>(srcImage.height), pfGUID,
```
hr returns error: Invalid Args

Format: DXGI_FORMAT_R16G16B16A16_UNORM
Slice size: 3200000000 bytes (still less that UINT32_MAX of 4294967295.)
Source Image: 20,000 x 20,000 x 16bit x2 channels Geo .TIFF file (763mb)
Can provide the image if I can find a place to upload to.

It appears that the new 4GB check is inadequate, instead WIC internal limit may be 2GB?
This .tiff ends up taking more memory due to 2 channels (elevation + alpha) being converted to 4 channels, even so, geotiff images can be very large.

**Comment by walbourn** [comment]
Doing some digging into the WIC source code, it looks like you are hitting this issue:

```
if (SUCCEEDED(hr) && (nHeight >= INT_MAX / cbStride))
{
  / / E_INVALIDARG;
}
```

**Comment by greg-churchillnavigation** [comment]
That makes sense.
I didn't see any limits mentioned in the docs on [CreateBitmapFromMemory](https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicimagingfactory-createbitmapfrommemory)
Perhaps normal use expects some kind of capability query before use.

I considered using a *NON_WIC flag, but I thought the code path always used WIC and failed before reaching the filter configuration. I could be wrong.
