### ISSUE TITLE
loading mipmaps with dx12 using LoadFromDDSFile

### ISSUE THREAD

**Issue by vichoconejeros** [microsoft/DirectXTex#174]
Hi

I can't find a good example on how to load the mipmaps information using LoadFromDDSFile, the mipmaps are there(11 mipmaps as it's a 1024x1024 picture) so I would like to skip the mipmap generation and just copy the data.

Is there a way for doing this without having to do the generation either in cpu or gpu?

**Comment by walbourn** [comment]
For details on using DirectXTex's solution for loading a DDS file and creating a texture, see [the wiki](https://github.com/microsoft/DirectXTex/wiki/CreateTexture) and in particular the use of ``PrepareUpload``.

Keep in mind that DirectXTex is a heavy-weight library designed for tools. If you just need to load a ``DDS`` file and create a texture from it at runtime, a light-weight solution is to use [DDSTextureLoader](https://github.com/microsoft/DirectXTK12/wiki/DDSTextureLoader). There's a version integrated into [DirectX Tool Kit for DX12](https://github.com/microsoft/DirectXTK12/wiki/Getting-Started) that manages the upload for you, or you can use the standalone version in the DirectXTex package.
