### ISSUE TITLE
Error in ExtendedBMP.cpp

### ISSUE THREAD

**Issue by Zwaliebaba** [microsoft/DirectXTex#181]
In line 185 it now says:

    hr = LoadFromWICMemory(bmpData.get(), bmpSize, flags, metadata, image);
    if (FAILED(hr))
        return hr;

    hr = LoadFromExtendedBMPMemory(bmpData.get(), bmpSize, metadata, image);
    if (FAILED(hr))
        return hr;

but the function LoadFromExtendedBMPMemory should only be called when LoadFromWICMemory is failing, but now it calls it all the time. More like:

 hr = LoadFromWICMemory(bmpData.get(), bmpSize, flags, metadata, image);
    if (FAILED(hr))
   {
    hr = LoadFromExtendedBMPMemory(bmpData.get(), bmpSize, metadata, image);
}
        return hr;

**Comment by walbourn** [comment]
Thanks. Good catch...

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/73dfcec9a1add113720aec3b945d72776db86fe5)
