### ISSUE TITLE
Some minor errors in C++ code

### ISSUE THREAD

**Issue by Kubera-Info** [microsoft/DirectXTex#182]
A PVS Studio detected a few errors in the C++ listings.
I have copied one sample:
`V549 The first argument of 'min' function is equal to the second argument. ScreenGrab12.cpp 1021size_t msize = std::min<size_t>(rowPitch, rowPitch);
`
The source would be a bit better after scanning by such software.
Would you check MS projects against such problems, please?

**Comment by walbourn** [comment]
I can only address the warnings you specifically list, but I've fixed this instance. I make regular use of Visual C++ ``/analyze`` static code analyzer, but I'm happy to get reports of bugs like this to look at.

**Comment by Kubera-Info** [comment]
Dear Sir!

The VIsual Studio's analyzer detects a bit different issues, both should be used :)

This code is the open source. It looks like the PVS Studio may be free of charge for open code developers.
In this situation, I publish here other minor errors. How hope it is OK.
```
V560 A part of conditional expression is always false: RequiredSize > SIZE_T (- 1). d3dx12.h 2051
V547 Expression 'pRowSizesInBytes[i] > SIZE_T (- 1)' is always false. d3dx12.h 2067
V547 Expression 'MemToAlloc > 0xffffffffffffffffui64' is always false. d3dx12.h 2103
V522 There might be dereferencing of a potential null pointer 'pParameters_1_0'. d3dx12.h 2210
V522 There might be dereferencing of a potential null pointer 'pDescriptorRanges_1_0'. d3dx12.h 2244
V1020 The function exited without calling the 'HeapFree' function. Check lines: 2276, 2198. d3dx12.h 2276
V1020 The function exited without calling the 'HeapFree' function. Check lines: 2276, 2232. d3dx12.h 2276
V1016 Expression 'SubobjectType < 0' is always false. d3dx12.h 2972
V1037 Two or more case-branches perform the same actions. Check lines: 451, 479 DDSTextureLoader12.cpp 451
V525 The code contains the collection of similar blocks. Check items '0x001f', '0x001f', '0x000f' in lines 697, 701, 708. DDSTextureLoader12.cpp 697
V560 A part of conditional expression is always true: texture. DDSTextureLoader12.cpp 1541
V1003 The macro 'ISBITMASK' is a dangerous expression. The parameters 'r', 'g', 'b', 'a' must be surrounded by parentheses. DDSTextureLoader12.cpp 638
V1037 Two or more case-branches perform the same actions. Check lines: 376, 404 ScreenGrab12.cpp 376
V547 Expression 'dstRowPitch > 0xffffffffui32' is always false. ScreenGrab12.cpp 888
V547 Expression 'dstRowPitch > 0xffffffffui32' is always false. ScreenGrab12.cpp 1092
```

P. S.
Please check other projects because of these errors.

**Comment by walbourn** [comment]
Thanks.

The V1037 is a good tweak. Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/e53a13e8c12a8165a99454e7ecc2d9dee18751d5).

The rest are false-positive warnings (or intentional for handling x86 vs x64 that are optimized out by the compiler). The D3DX12.H header also has some SAL annotations that let the Visual C++ /analyze to understand more that the PVS Studio doesn't consume.
