### ISSUE TITLE
Add DirectXTex to Conan

### ISSUE THREAD

**Issue by b2soft** [microsoft/DirectXTex#183]
Since Modern C++ way is to use Conan, I suggest to add DirectXTex to Conan. It will further simplify library installation and using.

**Comment by walbourn** [comment]
You are referring to https://conan.io/, correct?

**Comment by b2soft** [comment]
> 
> 
> You are referring to https://conan.io/, correct?

Correct, I'm about to add ability to install DirectXTex from Conan.
Here you can find how to create a recipe and how to create PR for center repo:
https://github.com/conan-io/conan-center-index/wiki

**Comment by walbourn** [comment]
Currently I provide VC++ projects, CMake support, and NuGet publishing.

I have been asked to support [VCPkg](https://github.com/microsoft/vcpkg) but that technology assumes you always have a DLL version of the library, which I don't believe is a good match for these utilities.

How does Conan differ from these solutions?

**Comment by walbourn** [comment]
All my GitHub projects including this one are now fully supported with [vcpkg](https://github.com/microsoft/vcpkg/tree/master/ports/directxtex).
