### ISSUE TITLE
gif transparency is lost using texassemble

### ISSUE THREAD

**Issue by vichoconejeros** [microsoft/DirectXTex#185]
Hi
I'm trying to convert the next gif to dds using texassemble ![image](https://acegif.com/wp-content/gifs/fire-65.gif)

it keeps the transparency of the first frame, but the next are missed
![image](https://user-images.githubusercontent.com/10147674/85978602-0c982600-b9ad-11ea-8fdd-cb904e6a38de.png)
![image](https://user-images.githubusercontent.com/10147674/85978622-17eb5180-b9ad-11ea-865f-59266c8f54c4.png)

**Comment by walbourn** [comment]
Thanks for the repro. I'll take a look,

**Comment by walbourn** [comment]
I wasn't handling transparency at all correctly. That will teach me to use an animated gif with a black background as my test :)

Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/58164bbabaa585de3c3f9f66213938512e669847)
