### ISSUE TITLE
CaptureTexture for DX12 doesn't support textures with 4Kb alignment

### ISSUE THREAD

**Issue by djbelyak** [microsoft/DirectXTex#187]
During capturing 4Kb aligned textures in DX12 occurs an error in the `Capture` procedure.
D3D12 Debug Layer reports the error `#721 CREATERESOURCE_INVALIDALIGNMENT`

**Comment by walbourn** [comment]
Looks like I just need to retry with a 0 alignment if the copied alignment fails.

https://asawicki.info/news_1726_secrets_of_direct3d_12_resource_alignment

**Comment by walbourn** [comment]
Actually, I think I should just use 0 alignment in all cases here for the readback and if I need to do a MSAA resolve.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/bfa3a11aeebf8b21c0ee41f3d5a1a1b45294d8a6).

Also fixed it in [DirectXTK12](https://github.com/microsoft/DirectXTK12/commit/b603c5653542216ef6aae3c42dc37a977fe8b2a6).
