### ISSUE TITLE
DirectXTexConvert.cpp UseWicConversion returns true for formats not supported for 'WicConversion' 

### ISSUE THREAD

**Issue by BAD-AL** [microsoft/DirectXTex#189]
When passing a tformat or sformat of 

- DXGI_FORMAT_B5G6R5_UNORM
- DXGI_FORMAT_R8_UNORM
- DXGI_FORMAT_B5G5R5A1_UNORM

 to the 'UseWicConversion' function in file 'DirectXTexConvert.cpp' returns 'true' and then when  the 'DirectX::Convert' function tries to convert from these formats, it fails.
Returning 'false' for these values in 'UseWicConversion' seems to allow the image to convert successfully to DXGI_FORMAT_B8G8R8A8_UNORM via  the 'ConvertCustom()' function inside 'DirectXTex.cpp'.

**Comment by walbourn** [comment]
What OS version are you using?

**Comment by BAD-AL** [comment]
Windows 10, 64-bit build

**Comment by walbourn** [comment]
Sorry, which build? Also, what function in particular is failing?

**Comment by BAD-AL** [comment]
Sorry...
My Build is in the following directory:
Z:\git\vcpkg\buildtrees\directxtex\src\jun2020b-16a3afffb8\DirectXTex
So the build is from June.

The 'DirectX::Convert' Function is failing.
As I step through in the debugger, I can see the 'UseWICConversion' function to return true with the formats mentioned, causing the convert to fail.

**Comment by walbourn** [comment]
How exactly do you see a failure? Does it return a failed value from ``IWICFormatConverter::CanConvert`` or somewhere else?

My test suite defintely covers cases like this, which work. For example, I just tried a ``DXGI_FORMAT_B5G5R5A1_UNORM`` -> ``DXGI_FORMAT_R8_UNORM`` case and it (a) took the WIC code path, (b) got a ``canConvert`` true result from ``IWICFormatConverter``, and (c) completed the entire conversion path.

Also, you have explicitly initialized COM on the calling thread, correct?

**Comment by walbourn** [comment]
Note if I do not initialize COM in my tests, then the HRESULT from ``ConvertUsingWIC`` is ``E_NOINTERFACE``. If that's what you are getting, the problem is that you didn't initialize COM.

**Comment by BAD-AL** [comment]
Ok, it does look like I skipped the com initialize in this case.
Do you have the test cases on GitHub?
I've also got messed up looking images converting to 'DXGI_FORMAT_R8G8B8A8_UNORM' from 
DXGI_FORMAT_B4G4R4A4_UNORM 
DXGI_FORMAT_A8_UNORM       
DXGI_FORMAT_R8G8_UNORM   
And I'd like to see if these test cases are covered too. 
It would also be incredibly helpful for anyone wanting to submit a pr to be able to run regression tests

**Comment by walbourn** [comment]
I'll take a look at those other cases.  The test suite is actually linked from the side-bar on the [wiki](https://github.com/microsoft/DirectXTex/wiki).

It's here: https://github.com/walbourn/directxtextest/wiki

**Comment by BAD-AL** [comment]
That's awesome. 
Thank you for the links and thank you for being incredibly responsive to this project. :)

**Comment by walbourn** [comment]
The 'direct conversion' of ``DXGI_FORMAT_R8G8B8A8_UNORM`` -> ``DXGI_FORMAT_A8_UNORM`` should just contain the alpha channel from the original image, RGB is ignored.

``DXGI_FORMAT_R8G8B8A8_UNORM`` -> ``DXGI_FORMAT_R8G8_UNORM`` is just going to copy R & G and ignore blue/alpha channels in the original image. You can control which channels are copied via the ``TEX_FILTER_RGB_COPY_RED``,  ``TEX_FILTER_RGB_COPY_GREEN ``, and ``TEX_FILTER_RGB_COPY_BLUE`` flags.

``DXGI_FORMAT_R8G8B8A8_UNORM`` -> ``DXGI_FORMAT_B4G4R4A4_UNORM``  is pretty harsh because of the loss of bit-count and you should consider enabling ``TEX_FILTER_DITHER`` or ``TEX_FILTER_DITHER_DIFFUSION``.

**Comment by walbourn** [comment]
They all look correct to me.

Keep in mind that the ``DXGI_FORMAT_R8G8_UNORM`` -> ``DXGI_FORMAT_R8G8B8A8_UNORM`` case is going to result in an empty blue channel. If you are trying to reconstuct the Blue channel assuming the R/G channels are x2 biased normal information, see the ``reconstructz`` switch in [texconv](https://github.com/microsoft/DirectXTex/blob/master/Texconv/texconv.cpp).
