### ISSUE TITLE
texdiag not recognize BC1a (bc1 with 1 bit alpha); texconv not correct work with bc3 normal map

### ISSUE THREAD

**Issue by Bxaa** [microsoft/DirectXTex#191]
For texdiag BC1a = BC1
Why?!
It is serious problem while batch conversion or sorting textures!
Example bc1 with alpha:
https://drive.google.com/file/d/1j1j0z6LgloGtL9GsoXt6QddaQnMHjPPR/view?usp=sharing
***
bc3 no mip gamma correct

**Comment by walbourn** [comment]
BC1 (a.k.a DXT1) does not have an explicit alpha channel. There is an encoding trick where if the two color end-points are one direction, then are 3 colors or fully transparent to pick from otherwise there are 4 colors. DirectXTex properly handles the alpha in your ``leatherrack01.dds`` file.

What are the command-line parameters you are using with ``texdiag`` that you believe is reporting incorrect information?


As for the BC3 issue, please provide the example image file and the command-line parameters you are providing to ``texconv``.

**Comment by Bxaa** [comment]
(!) [BC1 RGB 4 bpp | no alpha (a.k.a DXT1)] != [BC1a RGBA 4 bpp | alpha (a.k.a DXT1)] (nvidia texture exporter specification)

Example with leatherrack01.dds:
--------------------------------------------------------------------
convert texture.dds -verbose info: (get info with imagemagik convert)
-BC1a
alpha: 1-bit (if not present - texture is BC1)
alpha:
min: 255 (1) Seems to be opaque...                                                                                                
max: 255 (1) '--\\--\\--
mean: 255 (1) '--\\--\\--
standard deviation: 0 (0)
kurtosis: -3 <<< !!! (if 0 we got a simple bc1 with activated alpha, but not used transparency. Can processed like simple BC1 and remove alpha)
skewness: 0

How about add BC1(A)_UNORM to texdiag info?
width = 1024
height = 1024
depth = 1
mipLevels = 11
arraySize = 1
format = BC1a_UNORM '<<<
dimension = 2D
alpha mode = Unknown
images = 11
pixel size = 682 (KB)

Actually this is the question...

**Comment by Bxaa** [comment]
***
(!) [BC1 RGB 4 bpp | no alpha (a.k.a DXT1)] != [BC1a RGBA 4 bpp | alpha (a.k.a DXT1)] (nvidia texture exporter specification)
***
Example with mask.dds:
https://drive.google.com/file/d/1SeAJIafb92yh76BjspgE5UVLiN2B7Sfc/view?usp=sharing
--------------------------------------------------------------------
convert texture.dds -verbose info: (get info with imagemagik convert)
-BC1a
alpha: 1-bit (if not present - texture is BC1)
alpha:
min: 255 (1) Seems to be opaque...                                                                                                
max: 255 (1) '--\\--\\--
mean: 255 (1) '--\\--\\--
standard deviation: 0 (0)
kurtosis: -3 <<< !!! (if 0 we got a simple bc1 with activated alpha, but not used transparency. Can processed like simple BC1 and remove alpha)
skewness: 0

How about add BC1(A)_UNORM to texdiag info?
width = 1024
height = 1024
depth = 1
mipLevels = 11
arraySize = 1
format = BC1a_UNORM '<<<
dimension = 2D
alpha mode = Unknown
images = 11
pixel size = 682 (KB)
***
Actually this is the question...

**Comment by Bxaa** [comment]
BC3 issue
***
input(B8G8R8A8_UNORM).dds  - input texture
----------------------------------------------------
texconv -y -if point -srgb -ft DDS -f BC3_UNORM -o texconv(BC3_bad).dds

nvtt_export -f 18 input(B8G8R8A8_UNORM).dds -o nvidia_exporter(BC3_good)_n.dds (-f 18 = BC3)
***
Textures and screens:
https://drive.google.com/file/d/1o7yAiqsMS6UupK4QQ0l7EDHTpUUafMoo/view?usp=sharing

**Comment by walbourn** [comment]
There is no "BC1A" format. It's just BC1 (DXTn). They are not distinct formats from the perspective of Direct3D. If you run ``texdiag analyze leatherrack01.dds`` you'll see that file has some 3 color blocks (i.e transparency).

Note that this exactly the kind of optimization the "DX10" alpha-mode metadata is supposed to enable. If you created the ``DDS`` with DirectXTex and used the "DX10" variant (you can force it with ``texconv`` using ``-dx10``) then it would include the alpha-mode metadata. It's the same as the Direct2D notion of alpha-mode on [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/dcommon/ne-dcommon-d2d1_alpha_mode). At load time this can help you determine if the texture actually needs alpha-blending or not.

**Comment by walbourn** [comment]
For the BC3 issue, the compressed data is basically identical. The problem is that texconv is writing 10 mips instead of 13. Of course, for BC format's anything smaller than 4x4 is just a copy, but should be creating the full mips...

**Comment by walbourn** [comment]
I just tried the latest texconv and I creates 13 mips. I think you are using an old version of DirectXTex and should upgrade to a newer release.

**Comment by Bxaa** [comment]
I have tried different filters (it is just example)
Version texconv 2020.7.2.1

**Comment by Bxaa** [comment]
> I just tried the latest texconv and I creates 13 mips. I think you are using an old version of DirectXTex and should upgrade to a newer release.

Can you upload texture (bc3 with 13 mips) i'll try it in test game?

**Comment by walbourn** [comment]
Can you verify you are running the right ``texconv``? The command-line you provide is not a valid one for the DirectXTex version:

```
texconv -y -if point -srgb -ft DDS -f input(B8G8R8A8_UNORM)_n.dds -o BC3_UNORM texconv(BC3_bad)_n.dds
```

Did you mean something like?

```
texconv -y -if point -srgb -ft DDS input(B8G8R8A8_UNORM)_n.dds -f BC3_UNORM -sx (bc3_bad)
```

**Comment by Bxaa** [comment]
***
Usage: texconv <options> <files>

   -r                  wildcard filename search is recursive
   -flist <filename>   use text file with a list of input files (one per line)

   -w <n>              width
   -h <n>              height
   -m <n>              miplevels
   -f <format>         format

   -if <filter>        image filtering
   -srgb{i|o}          sRGB {input, output}

   -px <string>        name prefix
   -sx <string>        name suffix
   -o <directory>      output directory
   -l                  force output filename to lower case
   -y                  overwrite existing output file (if any)
   -ft <filetype>      output file type

   -hflip              horizonal flip of source image
   -vflip              vertical flip of source image

   -sepalpha           resize/generate mips alpha channel separately
                       from color channels
   -keepcoverage <ref> Preserve alpha coverage in mips for alpha test ref

   -nowic              Force non-WIC filtering
   -wrap, -mirror      texture addressing mode (wrap, mirror, or clamp)
   -pmalpha            convert final texture to use premultiplied alpha
   -alpha              convert premultiplied alpha to straight alpha
   -at <threshold>     Alpha threshold used for BC1, RGBA5551, and WIC
                       (defaults to 0.5)

   -fl <feature-level> Set maximum feature level target (defaults to 11.0)
   -pow2               resize to fit a power-of-2, respecting aspect ratio

   -nmap <options>     converts height-map to normal-map
                       options must be one or more of
                          r, g, b, a, l, m, u, v, i, o
   -nmapamp <weight>   normal map amplitude (defaults to 1.0)

                       (DDS input only)
   -t{u|f}             TYPELESS format is treated as UNORM or FLOAT
   -dword              Use DWORD instead of BYTE alignment
   -badtails           Fix for older DXTn with bad mipchain tails
   -fixbc4x4           Fix for odd-sized BC files that Direct3D can't load
   -xlum               expand legacy L8, L16, and A8P8 formats

                       (DDS output only)
   -dx10               Force use of 'DX10' extended header
   -dx9                Force use of legacy DX9 header

                       (TGA output only)
   -tga20              Write file including TGA 2.0 extension area

                       (BMP, PNG, JPG, TIF, WDP output only)
   -wicq <quality>     When writing images with WIC use quality (0.0 to 1.0)
   -wiclossless        When writing images with WIC use lossless mode
   -wicmulti           When writing images with WIC encode multiframe images

   -nologo             suppress copyright message
   -timing             Display elapsed processing time

   -singleproc         Do not use multi-threaded compression
   -gpu <adapter>      Select GPU for DirectCompute-based codecs (0 is default)
   -nogpu              Do not use DirectCompute-based codecs

   -bc <options>       Sets options for BC compression
                       options must be one or more of
                          d, u, q, x
   -aw <weight>        BC7 GPU compressor weighting for alpha error metric
                       (defaults to 1.0)

   -c <hex-RGB>        colorkey (a.k.a. chromakey) transparency
   -rotatecolor <rot>  rotates color primaries and/or applies a curve
   -nits <value>       paper-white value in nits to use for HDR10 (def: 200.0)
   -tonemap            Apply a tonemap operator based on maximum luminance
   -x2bias             Enable *2 - 1 conversion cases for unorm/pos-only-float
   -inverty            Invert Y (i.e. green) channel values

   <format>: R32G32B32A32_FLOAT R32G32B32A32_UINT R32G32B32A32_SINT
      R32G32B32_FLOAT R32G32B32_UINT R32G32B32_SINT R16G16B16A16_FLOAT
      R16G16B16A16_UNORM R16G16B16A16_UINT R16G16B16A16_SNORM
      R16G16B16A16_SINT R32G32_FLOAT R32G32_UINT R32G32_SINT
      R10G10B10A2_UNORM R10G10B10A2_UINT R11G11B10_FLOAT R8G8B8A8_UNORM
      R8G8B8A8_UNORM_SRGB R8G8B8A8_UINT R8G8B8A8_SNORM R8G8B8A8_SINT
      R16G16_FLOAT R16G16_UNORM R16G16_UINT R16G16_SNORM R16G16_SINT
      R32_FLOAT R32_UINT R32_SINT R8G8_UNORM R8G8_UINT R8G8_SNORM
      R8G8_SINT R16_FLOAT R16_UNORM R16_UINT R16_SNORM R16_SINT
      R8_UNORM R8_UINT R8_SNORM R8_SINT A8_UNORM R9G9B9E5_SHAREDEXP
      R8G8_B8G8_UNORM G8R8_G8B8_UNORM BC1_UNORM BC1_UNORM_SRGB BC2_UNORM
      BC2_UNORM_SRGB BC3_UNORM BC3_UNORM_SRGB BC4_UNORM BC4_SNORM
      BC5_UNORM BC5_SNORM B5G6R5_UNORM B5G5R5A1_UNORM B8G8R8A8_UNORM
      B8G8R8X8_UNORM R10G10B10_XR_BIAS_A2_UNORM B8G8R8A8_UNORM_SRGB
      B8G8R8X8_UNORM_SRGB BC6H_UF16 BC6H_SF16 BC7_UNORM BC7_UNORM_SRGB
      AYUV Y410 Y416 YUY2 Y210 Y216 B4G4R4A4_UNORM
      DXT1 DXT2 DXT3 DXT4 DXT5 RGBA BGRA FP16 FP32 BPTC
      BPTC_FLOAT

   <filter>: POINT LINEAR CUBIC FANT BOX TRIANGLE POINT_DITHER
      LINEAR_DITHER CUBIC_DITHER FANT_DITHER BOX_DITHER TRIANGLE_DITHER
      POINT_DITHER_DIFFUSION LINEAR_DITHER_DIFFUSION CUBIC_DITHER_DIFFUSION
      FANT_DITHER_DIFFUSION BOX_DITHER_DIFFUSION TRIANGLE_DITHER_DIFFUSION

   <rot>: 709to2020 2020to709 709toHDR10 HDR10to709 P3to2020
      P3toHDR10

   <filetype>: BMP JPG JPEG PNG DDS TGA HDR TIF TIFF WDP HDP JXR
      PPM PFM

   <feature-level>: 9.1 9.2 9.3 10.0 10.1 11.0 11.1 12.0 12.1

   <adapter>:
      0: VID:10DE, PID:1C03 - NVIDIA GeForce GTX 1060 6GB
      1: VID:8086, PID:3E92 - Intel(R) UHD Graphics 630
      2: VID:1414, PID:008C - Microsoft Basic Render Driver
***

**Comment by Bxaa** [comment]
Did you mean something like?

texconv -y -if point -srgb -ft DDS input(B8G8R8A8_UNORM)_n.dds -f BC3_UNORM

Yes. I wrote from memory and may not have written exactly

**Comment by walbourn** [comment]
```
nvidia_exporter(BC3_good)_n.dds
        width = 2048
       height = 4096
        depth = 1
    mipLevels = 13
    arraySize = 1
       format = BC3_UNORM
    dimension = 2D
   alpha mode = Unknown
       images = 13
   pixel size = 10922 (KB)
```

and

```
texconv(BC3_bad)_n.dds
        width = 2048
       height = 4096
        depth = 1
    mipLevels = 10
    arraySize = 1
       format = BC3_UNORM
    dimension = 2D
   alpha mode = Unknown
       images = 10
   pixel size = 10922 (KB)
```

both have basically the same data. I'm not sure why your miplevel says 10 instead of 13 (maybe you used ``-m 10``?). The texconv version has harsher mipmaps because you used ``-if point`` instead of the default.

The one I sent you is the same except for two additional mips that look like the nvidia version.

You may want to dig a bit deeper into your code to see where you are treating these two files differently.

**Comment by Bxaa** [comment]
no difference -m 10 -m 1 -m 0 - m 13 (nvidia_exporter with any count of mip - couse no problem in game)
This is not the reason.
Texture after converting to bc3 using texconv not correctly rendering in game

(!)Seems to be wrong alpha handling for mip mapping...

p/s found another issue with r8g8b8a8_(S)norm (input format is r8g8b8a8_unorm)
without -dx10 output dds with wrong color
with -dx10 color normal, but got broken dds header (null pointer to image)
Do you need texture samples?

**Comment by walbourn** [comment]
You should try ``-sepalpha`` with ``texconv`` then. WIC (used by DirectXTex) uses premultipled-alpha so if your alpha channel is something other than transparency, the results will be wrong.

**Comment by Bxaa** [comment]
I've tried this already - it doesn't help

**Comment by walbourn** [comment]
Well, I'm motivated to fix bugs here if they are present, but I'm having no luck remote diagnosing the problem.

From what I can tell, texconv with the following options is producing nearly identical texture data as the nvidia tool:

```
texconv "input(B8G8R8A8_UNORM)_n.dds" -sepalpha -f BC3_UNORM -sx (texconv) -m 0 -if FANT
```

**Comment by Bxaa** [comment]
Thanks for your help, maybe a solution will be found later. 
I will use nvidia tool for bc3 normal map as an alternative.

**Comment by walbourn** [comment]
Out of curiosity, what are you using to render that scene, and in particular what code are you using to load the DDS form disk for rendering?
