### ISSUE TITLE
TGA Loader can lose data in the alpha channel in some cases

### ISSUE THREAD

**Issue by magcius** [microsoft/DirectXTex#195]
In https://github.com/microsoft/DirectXTex/wiki/TGA-I-O-Functions#implementation-notes , there appears to be this line:

> For 16-bit and 32-bit truecolor images, there is a special-case fixup if the entire alpha channel is 0 it is assumed to be fully opaque.

Is there a way to disable this behavior, or would it be possible to add one? It's not uncommon in art pipelines for alpha to have a different meaning than "transparency", and in our case, we have a behavior where the artists need a fully-zero alpha channel. The current workaround is to place a pixel with an alpha value of 1 in the top left corner, which isn't optimal.

**Comment by walbourn** [comment]
Fair enough. I'll look at adding defaulted flags to the TGA functions
