### ISSUE TITLE
TexConv microsoft documentation is entirely inaccurate?

### ISSUE THREAD

**Issue by opusGlass** [microsoft/DirectXTex#202]
Apologies if this is some kind of user error but, the parameters listed in [Microsoft TexConv documentation](https://docs.microsoft.com/en-us/azure/remote-rendering/resources/tools/tex-conv) do not seem to be accurate. They do not match up with the [github documentation](https://github.com/microsoft/DirectXTex/wiki/Texconv) and when I try the parameters from Microsoft the program does not run and instead displays the "--help" info. 

Did the parameters change?

The microsoft documentation includes instructions for mapping channels from input to output, which I need. I need to do the following 3 operations:
1) convert RGB channels from DDS to a 3-channel PNG/TGA, discarding the A channel. 
2) convert A channel from DDS to fill all channels in a 3-channel PNG/TGA, discarding the RGB channels.
3) combine and convert RGB from PNG_1 and R from PNG_2 into a single 4-channel RGBA DDS.

But I don't see any way I can do that with the parameters as specified on the github documentation.

**Comment by walbourn** [comment]
That's some unrelated tool. In fact, I have never heard of it until now :) It looks like something from the Azure and/or HoloLens team.

The 'texconv' tool in DirectXTex is modelled after the legacy DirectX SDK tool 'texconv'.

**Comment by opusGlass** [comment]
> That's some unrelated tool. In fact, I have never heard of it until now :) It looks like something from the Azure and/or HoloLens team.
> 
> The 'texconv' tool in DirectXTex is modelled after the legacy DirectX SDK tool 'texconv'.

Wait, so are you saying there are 2 completely unrelated tools that are:
-both named "texconv.exe"
-both released by microsoft
-both used to convert to and from DDS
-both are command-line tools

That seems astonishing to me.

Anyway, is there no way to split out alpha channels and recombine them in DirectXTex's TexConv?

**Comment by walbourn** [comment]
Apparently, yes :)

I'm tracking down the people who created the "Azure" version to see what's up there, but they didn't use the legacy DirectX SDK command-line structure for that tool. It may well be using DirectXTex for the I/O.

I'm not sure I quite follow what operation you are trying to do here. What is the format of the DDS file(s) you are starting with?

My [texassemble](https://github.com/microsoft/DirectXTex/wiki/Texassemble) using ``merge`` should handle that 3rd step for you.

**Comment by opusGlass** [comment]
Wow, that's remarkable if true. I can't find the Azure version of TexConv anywhere though. Thank you for reaching out to them.

For steps 1 and 2, basically I'm saying I need to split an image's RGB and A out into separate images. The output images from these steps could be stored either as TGA or PNG format, I prefer PNG.

The input files for these steps are in a variety of formats. I actually have TGA and DDS copies of most of these input images, so I'd prefer to use the TGA inputs when I can choose, to avoid the compression. But some of the input files are only in DDS, with various formats (some BC1, some BC5, possibly others). So I appreciated that the Azure tool doesn't require the input image format to be specified when mapping channels.

**Comment by walbourn** [comment]
OK, so you need the opposite of ``texassemble merge``...

**Comment by opusGlass** [comment]
That's correct, the inverse of texassemble merge. Is there any consideration of adding something like that?

**Comment by walbourn** [comment]
You don't need step 1. You can just feed the original RGB into ``texassemble merge`` as the RGB thing.

Step 2 is ``texconv -f A8_UNORM -ft PNG`` but that just writes the alpha channel from the original, ignoring RGB. You want an 'monochrome average' of rgb.

Step 3 is ``texassemble merge``.

**Comment by walbourn** [comment]
Actually, ``texconv -f R8_UNORM -ft PNG`` works for step 2 because it generates a single channel as the luminance conversion of the input 3 channels. Then you can do ``texconv -f R8G8B8A8_UNORM`` on that second result which will expand it out to RGB.

``texassemble merge`` always reads the blue channel from the second image for the alpha (which is what the legacy DXTex tool did which is what I modelled it after).

**Comment by walbourn** [comment]
I should probably have some extra options for merge that let you read from an arbitrary R, G, B, or A) channel in the second image, or from 'rgb' average luminance from the second image to be a little more general. That would make your process basically a single call to ``texassemble merge originalimage1.dds originalimage2.dds newimage.dds``.

**Comment by opusGlass** [comment]
> Actually, `texconv -f R8_UNORM -ft PNG` works for step 2 because it generates a single channel as the luminance conversion of the input 3 channels. Then you can do `texconv -f R8G8B8A8_UNORM` on that second result which will expand it out to RGB.

Unfortunately this doesn't work - the first command outputs a 4-channel image with R,G,B set to 1 and A preserved from the original. If it exported only A as single channel image that would work but does not.
