### ISSUE TITLE
Modify TexConv A8_UNORM to export a single-channel image

### ISSUE THREAD

**Issue by opusGlass** [microsoft/DirectXTex#204]
> OK, so you need the opposite of ``texassemble merge``...

_Originally posted by @walbourn in https://github.com/microsoft/DirectXTex/issues/202#issuecomment-728335029_

> [texconv -f A8_UNORM] outputs a 4-channel image with R,G,B set to 1 and A preserved from the original. [...] R8_UNORM exports the R channel only as a single-channel image. If A8_UNORM exported a single channel like R8_UNORM does, it would work.

_Originally posted by @opusGlass in https://github.com/microsoft/DirectXTex/issues/202#issuecomment-729280680_

It is useful during image processing to have the Alpha channel separated from the RGB channels as 2 separate images, where the alpha can then be treated as an image rather than as a transparency layer. Then later the 2 images can be recombined.
To achieve this, the Alpha image can either be a single channel grayscale, or alternatively it can be a 3-channel with identical values in each channel (effectively making it grayscale).

Currently the A8_UNORM behaves differently from R8_UNORM in that it actually exports a 4-channel image. The first 3 channels are padded with white, so the actual data is only exported into the A channel, preventing it from solving my issue. 

If it is intended that A8_UNORM behaves this way, then I would ask to please implement an option for the R8_UNORM format that allows us to choose one of the 4 channels as the source data, instead of only allowing the R channel to be exported independently. This would also solve my issue.

**Comment by walbourn** [comment]
Maybe a general channel swizzle would be useful here. Something like ``-swizzle:aaaa`` which puts the alpha in all four channels, or ``-swizzle:rrra`` which does red in three channels plus a, etc.

**Comment by opusGlass** [comment]
That would be perfect.
