### ISSUE TITLE
texconv.exe does not return exit code different from 0 on failure

### ISSUE THREAD

**Issue by scrontch** [microsoft/DirectXTex#215]
I'm trying to use texconv.exe as one of different steps in an automated script.
I realized texconv.exe does not return an exit code different from 0 even if it fails, which makes error detection difficult in scripted environments.
Could you please return a non-zero exit code on failures?
Thank you.

**Comment by walbourn** [comment]
Fixed in this commit: https://github.com/microsoft/DirectXTex/commit/2a1a884507544e999071366a4c571c6212dc9bc6
