### ISSUE TITLE
Add ability to scale to a percentage of base size

### ISSUE THREAD

**Issue by NielsGx** [microsoft/DirectXTex#216]
Hello,
It would be great if we could rescale a DDS file to a percentage of its base size.
I would use it to resize some dds files to 50%.

If it's already possible, please let me know

Thanks

**Comment by walbourn** [comment]
Typically DDS files contain mip-map levels, so they already contain 'scaled' versions. The [DDSTextureLoader](https://github.com/Microsoft/DirectXTK/wiki/DDSTextureLoader) allows you to specify a max size and the loader 'skips' the larger mipmap levels.

Is that helpful?
