### ISSUE TITLE
Batch file code

### ISSUE THREAD

**Issue by noire90** [microsoft/DirectXTex#217]
A Batch file code to add an alpha channel inside my DXT5 .dds files, please?!

**Comment by walbourn** [comment]
Can you clarify your inputs a bit more? Do you have two source images, one of which is alpha?

**Comment by noire90** [comment]
Thanks for answering. I have some .dds file with mipmap. I need to add an alpha inside them to remove the transparency.

>

**Comment by walbourn** [comment]
You need to add an all opaque alpha channel then...

**Comment by noire90** [comment]
I understood in conclusion that I need a code to remove the alpha channel from my dds file. to remove transparency from them... Can you help me with this? I'm trying to find solution from days on line but I failed.

**Comment by walbourn** [comment]
I updated texconv's ``-swizzle`` in [this commit](https://github.com/microsoft/DirectXTex/commit/21202f09dc43f6c21c23e52b74335ccb13110409) so it can now set 0 or 1 values, so this case should be:

```
texconv -swizzle rgb1 sourceDXT5.dds  mydds
```

Keep in mind that to do this it has to uncompress, delete the mips, and recompress. If you don't want mips, use ``-m 1`` as well.
