### ISSUE TITLE
TexAssemble Merge fails with mipmapped input images

### ISSUE THREAD

**Issue by opusGlass** [microsoft/DirectXTex#222]
When using a mipmapped image as one of my inputs to TexAssemble Merge, I get the error message: "ERROR: Can't assemble complex surfaces". I confirmed that exporting the same image with mipmaps leads to error, without mipmaps does not.

My expectation was that it would use the base image (highest quality) as the source.

The fact it cannot is problematic when my source image comes to me pre-mipmapped. It is possible to work around by converting the image to an uncompressed format (to avoid accumulating compression losses) without mipmaps but this is not ideal since it is inconvenient and the uncompressed files take up significant space.

**Comment by walbourn** [comment]
I'd probably want to add an explicit switch that says "Yes, you can strip off mips for the inputs"... Maybe ``-stripmips`` :)

**Comment by opusGlass** [comment]
Works for me!

**Comment by walbourn** [comment]
Added in [this commit](https://github.com/microsoft/DirectXTex/commit/595b341626d2a4112bb6b9a3320d507f25c836fd)

**Comment by opusGlass** [comment]
@walbourn Unfortunately that commit does not seem to solve my issue. It now displays this error message when running "texasseble merge" on 2 images (2D images)
`-stripmips only applies to cube, volume, array, cubearray commands`

When running without "stripmips" I do see your new error message though:
`ERROR: Can't assemble using input mips. To ignore mips, try again with -stripmips`

**Comment by walbourn** [comment]
Ah, you are using ``merge``!  I'll check that...

**Comment by walbourn** [comment]
Sorry. ``merge`` should support this...

Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/7749ae75c62748166375c92727dea31dea5f94e1)

**Comment by opusGlass** [comment]
It works now, thank you for your help as always!
