### ISSUE TITLE
Texdiag FAILED (80004005) on tiny TGA

### ISSUE THREAD

**Issue by Bxaa** [microsoft/DirectXTex#226]
Notice:
Old texdiag version 2020.8.15.1 no error with glow.tga (images included in archive)

This is correct tga format, but texdiag failed:
https://drive.google.com/file/d/1r3fs0F2Rd-lMQDVJy0g1g96mocadKNSe/view?usp=sharing

**Comment by walbourn** [comment]
Thanks for the report. I didn't have a test case of TGA image quite that small... My logic to find the TGA 2.0 footer assumed the file was at least 26 bytes... your file is 21 bytes.

Working on a fix.

**Comment by walbourn** [comment]
Regression was introduced in the September 2020 release in [this commit](https://github.com/microsoft/DirectXTex/commit/836cabd0f9291af242a4965d52b8efe6b2755587).

Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/eda513ceba38db6f9b4691780f8de33197b32b1d).
