### ISSUE TITLE
Resize dds (filter question)

### ISSUE THREAD

**Issue by Bxaa** [microsoft/DirectXTex#232]
Hi,

Example:
I resize dds to lower size  (Input texture 8192x8192)
texconv.exe -w 2048 -h 2048  -m 1 -f DXT5 *.dds -o resized 

Is teconv support lanczos or similar quality filter (resize to lower)? 
(do you have plan to add lanczos)
What filter is a best texconv  implemented filter for resize in this case? (linear?)
Is mips correct regenerated while resize and what filter used for this (-if [filter] is global for resize and mips?)

thx

**Comment by walbourn** [comment]
Currently the DirectXTex resize supports box, bi-linear, cubic, and "triangle" (from the old D3DX).

I have additional filtering options on my [backlog](https://github.com/microsoft/DirectXTex/issues/3), although my past experience with those is that they are slow.

**Comment by walbourn** [comment]
Note that you can use ``-if FANT`` which for Windows Imaging Component (WIC) paths is the same as ``box`` for downscale with a ``linear`` for upscaling.
