### ISSUE TITLE
DDS mipmaps separated alpha (texconv)

### ISSUE THREAD

**Issue by Bxaa** [microsoft/DirectXTex#234]
**Hi, walbourn**
For dds textures with alpha '-sepalpha' implementation should be enabled by default for mipmaps images generating.

Without 'sepalpha' mipmap color channel loses some pixels while mip resizing (in one cases it is not critical, but sometime it broke all mipmaps and cause visual artifacts)

**Comment by walbourn** [comment]
It depends on if the alpha channel contains transparency or other kinds of information. WIC does the resizing by converting alpha to premultiplied-alpha then back.

The ``-sepalpha`` switch is specifically for the cases where the alpha channel doesn't contain transparency.

**Comment by Bxaa** [comment]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/DKX9YvP/image.png" alt="image" border="0"></a>
You get this without -sepalpha for all mipmaps if image contain alpha channel with image.
This is what I wanted to say

converting alpha to premultiplied-alpha then back - it corrupt colors channel on normal maps with alpha

**Comment by walbourn** [comment]
Some normal maps are encoded where the alpha channel is used for additional information. In that case, you need ``-sepalpha``.

**Comment by Bxaa** [comment]
_`Some normal maps are encoded where the alpha channel is used for additional information`_
No. this is simple bc3 with alpha (not special normal map)

Ок, we came to where we started :)
-sepalpha required for all dds with alpha...or you got issue with MIPS like on image Do not forget - alpha may used not only as simple mask.
