### ISSUE TITLE
TexConv swizzle possible incorrect order with swizzle vs 0/1

### ISSUE THREAD

**Issue by SamWetton** [microsoft/DirectXTex#241]
When using something like -swizzle aaa1, the 1 is applied first to the alpha channel before then setting rgb = a (which is now 1).
Not 100% sure this isn't intended but it doesn't seem intuitive so I think it's a bug? #

**Comment by walbourn** [comment]
The logic is currently:

```
XMVECTOR pixel = XMVectorSelect(inPixels[j], g_XMZero, zc);
pixel = XMVectorSelect(pixel, g_XMOne, oc);
outPixels[j] = XMVectorSwizzle(pixel,
    swizzleElements[0], swizzleElements[1], swizzleElements[2], swizzleElements[3]);
```

It sounds like you'd prefer:

```
XMVECTOR pixel = XMVectorSwizzle(inPixels[j],
    swizzleElements[0], swizzleElements[1], swizzleElements[2], swizzleElements[3]);
pixel = XMVectorSelect(pixel, g_XMZero, zc);
outPixels[j] = XMVectorSelect(pixel, g_XMOne, oc);
```

**Comment by SamWetton** [comment]
Yes, I think the second one makes more sense, though I'm not sure if I'm just skewed by my use case. Or if it was following some existing precedance.

**Comment by walbourn** [comment]
For texassemble, it's a permute (2 vectors) instead of a swizzle (1 vector):

```
XMVECTOR pixel1 = XMVectorSelect(inPixels[j], g_XMZero, zc);
pixel1 = XMVectorSelect(pixel1, g_XMOne, oc);
outPixels[j] = XMVectorPermute(pixel1, inPixels2[j],
    permuteElements[0], permuteElements[1], permuteElements[2], permuteElements[3]);
```

I think I convinced myself the 0/1 should go first in this case, but it probably makes more sense as:

```
XMVECTOR pixel = XMVectorPermute(inPixels[j], inPixels2[j],
    permuteElements[0], permuteElements[1], permuteElements[2], permuteElements[3]);
pixel = XMVectorSelect(pixel, g_XMZero, zc);
outPixels[j]  = XMVectorSelect(pixel, g_XMOne, oc);
```

Where the 0 and 1 is in the mask is where it should be in the 'result'...

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/b6aa25280bea536b58fae0bf03e3362d186651de)

**Comment by SamWetton** [comment]
Thank you :)
