### ISSUE TITLE
How can I read every pixel value in format DXGI_FORMAT_R16G16B16A16_FLOAT？

### ISSUE THREAD

**Issue by qjh5606** [microsoft/DirectXTex#242]
How can I read every pixel value in format DXGI_FORMAT_R16G16B16A16_FLOAT？
my code is:
`
const Image img = test_image.GetImages()[0];
uint16_t* dst = (uint16_t*)(img.pixels);
for (int rowIndex = 0; rowIndex < img.height; rowIndex++)
{
for (int colIndex = 0; colIndex < img.width; colIndex++)
{
R = dst[rowIndex * img.width * 4 + colIndex * 4 + 0];
G = dst[rowIndex * img.width * 4 + colIndex * 4 + 1];
B = dst[rowIndex * img.width * 4 + colIndex * 4 + 2];
}
`
but it went wrong.
how can i get correct value?

**Comment by walbourn** [comment]
I find it's easier to work with bytes for positioning and so you can use the ``img.rowPitch`` value which takes any alignment differences into account.

```
const Image img = test_image.GetImages()[0];
const size_t bpp = sizeof(float) * 4; // you can also get this with (BitsPerPixel(img.format) / 8);
for (size_t rowIndex = 0; rowIndex < img.height; rowIndex++)
{
    for (size_t colIndex = 0; colIndex < img.width; colIndex++)
    {
        const auto pixel = reinterpret_cast<uint16_t*>(img.pixels[rowIndex * img.rowPitch + colIndex * bpp]);

        R = pixel[0];
        G = pixel[1];
        B = pixel[2];
     }
}
```
