### ISSUE TITLE
Linear Filter bug when it wraps

### ISSUE THREAD

**Issue by jpownby-es** [microsoft/DirectXTex#243]
The _CreateLinearFilter() filtrer function adjusts the isrcB variable (the index) when encountering an edge case that should wrap, but the srcB variable doesn't have a corresponding adjustment. This leads to the weight that is calculated being wrong, which means that there is a bad row at the right and a bad column at the bottom of images.

There are different ways that it could be fixed, but the following is one proposed fix (I've also added some asserts to try and make the problem more obvious):

```
        if (size_t(isrcB) >= source)
        {
            if (wrap)
            {
                isrcB = 0;
                srcB -= float(source);
            }
            else
            {
                isrcB = ptrdiff_t(source) - 1;
                srcB = float(isrcB);
            }
        }
        assert((isrcB >= 0) && (size_t(isrcB) < source));
        assert((srcB >= 0.0f) && (srcB < float(source)));

        float weight = 1.0f + float(isrcB) - srcB;
        assert((weight >= 0.0f) && (weight <= 1.0f));
```

Also, FYI, at a quick glance I think that the _CreateCubicFilter() may have the same problem, but I don't have a specific test case with that and I didn't do any further experimentation.

**Comment by walbourn** [comment]
This code was adapted from code in D3DX9, and it looks like I introduced the subtle bug here. The "fix" is to move the weights computation before adjusting for wrap:

```
float srcB = (float(u) + 0.5f) * scale + 0.5f;

ptrdiff_t isrcB = ptrdiff_t(srcB);
ptrdiff_t isrcA = isrcB - 1;

float weight = 1.0f + float(isrcB) - srcB;

if (isrcA < 0)
{
    isrcA = (wrap) ? (ptrdiff_t(source) - 1) : 0;
}

if (size_t(isrcB) >= source)
{
    isrcB = (wrap) ? 0 : (ptrdiff_t(source) - 1);
}
```

**Comment by jpownby-es** [comment]
Ah yes, I like it, simpler than what I had :)

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/b11ad7b1c0897e550aa1783ea33bc3ac7ca2248f)
