### ISSUE TITLE
TexConv on Intel GPU

### ISSUE THREAD

**Issue by Kubera-Info** [microsoft/DirectXTex#244]
Would you, please, verify one problem:
1>reading Images\RV_Marble_2_baseColor.png (4096x4096 R8G8B8A8_UNORM 2D a:Opaque) as
1>[Using DirectCompute on "Intel(R) UHD Graphics 750"]
1> FAILED [compress] (887A0005: Wyst�pienie urz�dzenia GPU zosta�o zawieszone. U�yj obiektu GetDeviceRemovedReason, aby okre�li� odpowiedni� akcj�.)

This is an error on the complex .png image converted to texture BC7
On NVidia everythinhg works fine.

The problem exists on the newest app version (2021.8.2.1)

Example file:
https://www.kubera.info/ms/RV_Marble_2_baseColor.png

**Comment by walbourn** [comment]
Given the failure here, it's a driver bug. You should report the issue to Intel.

**Comment by Kubera-Info** [comment]
I highly appreciate the support
