### ISSUE TITLE
DirectX::LoadFromWICFile format error

### ISSUE THREAD

**Issue by 021xcy** [microsoft/DirectXTex#245]
I have a tif in DXGI_FORMAT_R16G16B16A16_FLOAT format. The DirectX::LoadFromWICFile interface reads the tif file and the format obtained is DXGI_FORMAT_R16G16B16A16_UNORM. Why is this?

**Comment by walbourn** [comment]
This is based on the behavior of the built-in TIF codec in the [Windows Imaging Component](https://docs.microsoft.com/en-us/windows/win32/wic/-wic-codec-native-pixel-formats).

| Decoder Pixel Formats | Encoder Pixel Formats |
-- | --
| GUID_WICPixelFormat1bppIndexed | GUID_WICPixelFormat1bppIndexed| 
|GUID_WICPixelFormat4bppIndexed | GUID_WICPixelFormat4bppIndexed|
|GUID_WICPixelFormat8bppIndexed | GUID_WICPixelFormat8bppIndexed|
|GUID_WICPixelFormatBlackWhite | GUID_WICPixelFormatBlackWhite|
|GUID_WICPixelFormat4bppGray | GUID_WICPixelFormat4bppGray|
|GUID_WICPixelFormat8bppGray | GUID_WICPixelFormat8bppGray|
|GUID_WICPixelFormat16bppGray | GUID_WICPixelFormat16bppGray|
|GUID_WICPixelFormat32bppGrayFloat | GUID_WICPixelFormat24bppBGR|
|GUID_WICPixelFormat24bppBGR | GUID_WICPixelFormat32bppBGRA|
|GUID_WICPixelFormat32bppBGRA | GUID_WICPixelFormat32bppCMYK|
|GUID_WICPixelFormat32bppPBGRA | GUID_WICPixelFormat48bppRGB|
|GUID_WICPixelFormat48bppRGB | GUID_WICPixelFormat64bppRGBA|
|GUID_WICPixelFormat32bppCMYK |  |
|GUID_WICPixelFormat40bppCMYKAlpha |  |
|GUID_WICPixelFormat64bppRGBA |  |
| GUID_WICPixelFormat64bppPRGBA |  |
|GUID_WICPixelFormat64bppCMYK |  |
|GUID_WICPixelFormat80bppCMYKAlpha |  |
|GUID_WICPixelFormat96bppRGBFloat* |  |
|GUID_WICPixelFormat128bppRGBAFloat |  |
|GUID_WICPixelFormat128bppPRGBAFloat| |

There's no direct support for ``GUID_WICPixelFormat64bppRGBAHalf``, so it converts it to some format internally.
