### ISSUE TITLE
DirectXTex/DirectXTex/DDS.h. possible wrong value of DDS_RESOURCE_MISC_TEXTURECUBE

### ISSUE THREAD

**Issue by Awkward-im** [microsoft/DirectXTex#247]
DDS_RESOURCE_MISC_TEXTURECUBE is 4
but D3D10_RESOURCE_MISC_FLAG and D3D11_RESOURCE_MISC_FLAG gives
D3D11_RESOURCE_MISC_TEXTURECUBE and D3D10_RESOURCE_MISC_TEXTURECUBE as 2.

**Comment by walbourn** [comment]
Where are you seeing it as "2"?

```
10.0.10586.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.10586.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.14393.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.14393.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.15063.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.15063.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.16299.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.16299.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.17134.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.17134.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.17763.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.17763.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.18362.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.18362.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.19041.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.19041.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.20348.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.20348.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.22000.0\um\d3d10.h:        D3D10_RESOURCE_MISC_TEXTURECUBE = 0x4L,
10.0.22000.0\um\d3d11.h:        D3D11_RESOURCE_MISC_TEXTURECUBE = 0x4L,
```

**Comment by Awkward-im** [comment]
sorry, i looked to
https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_resource_misc_flag
and
https://docs.microsoft.com/en-us/windows/win32/api/d3d10/ne-d3d10-d3d10_resource_misc_flag
i thinked, these consts going like 0,1,2,3,4,5
maybe i was wrong (i use pascal, not C)
typedef enum D3D10_RESOURCE_MISC_FLAG { D3D10_RESOURCE_MISC_GENERATE_MIPS,
D3D10_RESOURCE_MISC_SHARED, D3D10_RESOURCE_MISC_TEXTURECUBE,
D3D10_RESOURCE_MISC_SHARED_KEYEDMUTEX, D3D10_RESOURCE_MISC_GDI_COMPATIBLE }
;

вс, 12 сент. 2021 г. в 22:23, Chuck Walbourn ***@***.***>:

**Comment by Awkward-im** [comment]
Checked header file, value assigned there manually. So, i was wrong. Sorry

вс, 12 сент. 2021 г. в 22:23, Chuck Walbourn ***@***.***>:

**Comment by walbourn** [comment]
No problem. The Microsoft docs display for the enums is a little misleading I see in what the values might be...

For C/C++ programming, it's common practice to explicitly assign values for enums that represent flags instead of letting the compiler assign them. In fact, any time you are serializing the values to disk, you should always assign them to make sure future code edits don't break existing files.

BTW, you may want to read this blog post as well: https://walbourn.github.io/modern-c++-bitmask-types/
