### ISSUE TITLE
Support for 32k x 32k pixel textures

### ISSUE THREAD

**Issue by MalcolmTyrrell** [microsoft/DirectXTex#253]
It looks like the WIC library cannot load 32k textures. 

Stepping through the code, reveals that loading such a texture fails at [this line](https://github.com/microsoft/DirectXTex/blob/800aa853e82fd8ecf79b2492875d3fab9b81b929/DirectXTex/DirectXTexWIC.cpp#L689):

if (img->rowPitch > UINT32_MAX || img->slicePitch > UINT32_MAX)
    return HRESULT_E_ARITHMETIC_OVERFLOW;

This makes sense as the subsequent CopyPixels call has Uints parameters.

Is there way around this limitation?

Note that we are aware that DX can't use such large textures, but we'd like to be able to load them, in order to downscale them to a useable size.

**Comment by walbourn** [comment]
This is a limitation of the WIC API itself, and it's not always consistent from codec to codec what the maximum size actually is. Internally, WIC cannot handle any image whose *total uncompressed size in bytes* exceeds a 32-bit integer. For example, a 16k by 16k ``DXGI_FORMAT_R32G32B32A32_FLOAT`` image is too big.

This is true even for the 64-bit version of WIC.

I have modified DirectXTex to swap over to 'custom filtering' code whenever the data exceeds the WIC limits for many operations

Which file format are you trying to process?

**Comment by walbourn** [comment]
The maximum texture size supported by Direct3D is 16k by 16k. This is considered the upper-limit of size that can be correctly accessed with a single-precision floating-point u,v value. It might be better to consider using tiled textures for your case and break up the image into 16k x 16k chunks using some other tool.
