### ISSUE TITLE
Difference between WIC and non-WIC?

### ISSUE THREAD

**Issue by Guekka** [microsoft/DirectXTex#256]
Hello, I would like to know if there is any advantage to using WIC vs not using it (`TEX_FILTER_FORCE_NON_WIC`)

I tend to disable WIC because `DirectX::Resize` converts the texture to `R32G32B32A32` if WIC is used.

But is there any disadvantage in doing this? In terms of speed or quality?

Thanks

**Comment by walbourn** [comment]
In the original implementation of DirectXTex, my plan was to make everything use Windows Imaging Component (WIC) where possible. Over the years, I've run into various conflicts between the design points of WIC (desktop image manipulation like photos, etc.) and the needs of a dedicated texture processing library: treating of implicit vs. explicit sRGB color-spaces, filtering choices like D3DX TRIANGLE essential for odd-depth volume maps, etc.

In the end, I've implemented two paths for most, but not all, operations. To get a sense of when it was necessary to use WIC, see the logic in ``UseWICConversion`` in ``DirectXTexConvert.cpp``, and ``UseWICFiltering`` in ``DirectXTexMipMaps.cpp`` / ``DirectXTexResize.cpp``.

IF the ``DXGI_FORMAT_*`` you are using directly maps to one of the supported WIC formats, then WIC is likely faster for doing resize for classic 8-bit images. Whenever I find a format case that doesn't directly map to WIC, I often convert to FP32 and then use that for WIC to handle it. There are some cases that WIC can't handle even with a FP32 intermediary, and then I always use the "non-WIC" paths.

The 'custom filtering' (i.e. non-WIC) code paths are all implemented using [DirectXMath](https://github.com/microsoft/DirectXMath/) and therefore all pixels are converted to/from FP32 in the processing (typically per scanline).

If for your particular scenario it's having to convert to FP32 and then using WIC to Resize then back from FP32, it's probably the same speed or a little faster to just use the non-WIC paths.

**Comment by Guekka** [comment]
I see. Thanks for this quick and thorough answer!

**Comment by chloekek** [comment]
Another use case for `-nowic` is when running under Wine, whose WIC implementation [only supports nearest neighbor filtering](https://github.com/wine-mirror/wine/blob/15aec461174ae2f2568d63fa83f32576ede05a9c/dlls/windowscodecs/scaler.c#L352).
