### ISSUE TITLE
Standalone DDSloader11 requires dxguid.lib to run

### ISSUE THREAD

**Issue by stoopdapoop** [microsoft/DirectXTex#257]
DDSLoader11.cpp will fail to link with when included in a project unless dxguid.lib is loaded.

it references "WKPDID_D3DDebugObjectName" to set the debuginfo.

Obviously setting Debug Names is useful, but unless I'm missing something, there was no way to know that this is a requirement without running into this issue myself.  A note in the documentation would go a long way. I spent a fair amount of time trying to figure this out.

**Comment by walbourn** [comment]
I generally assume projects are linking against ``dxgi.lib``, ``d3d11.lib``, ``dxguid.lib``, and ``uuid.lib``. That said, I can add a pragma to the headers to help.

**Comment by walbourn** [comment]
https://github.com/microsoft/DirectXTex/commit/6489db58b46a2c15726fc4104e47d5f18f463da9
