### ISSUE TITLE
SaveToWICFile return 80004002

### ISSUE THREAD

**Issue by PTA00** [microsoft/DirectXTex#263]
this is my code.What do I need to check?
![image](https://user-images.githubusercontent.com/59364024/152489274-a75911e4-5a09-48dc-b11e-fe34ae986ed9.png)

**Comment by PTA00** [comment]
I noticed the return statement in the source code.No WIC support？
[https://github.com/microsoft/DirectXTex/blob/20e246af2bd5f18a7cc553323bac0f2320e3bd2e/DirectXTex/DirectXTexWIC.cpp#L1550](url)

**Comment by PTA00** [comment]
`bool iswic2 = false;
        auto pWIC = GetWICFactory(iswic2);
        if (!pWIC)
            return E_NOINTERFACE;`

**Comment by PTA00** [comment]
//
// MessageId: E_NOINTERFACE
//
// MessageText:
//
// No such interface supported
//
#define E_NOINTERFACE                    _HRESULT_TYPEDEF_(0x80004002L)

**Comment by walbourn** [comment]
Have you initialized COM in your application?

https://github.com/microsoft/DirectXTex/wiki/DirectXTex#initialization

**Comment by PTA00** [comment]
Sorry, I didn't notice that.
