### ISSUE TITLE
texconv -tonemap on Radiance HDR files seems to work better with JPG than PNG

### ISSUE THREAD

**Issue by jpark37** [microsoft/DirectXTex#276]
It feels like this shouldn't be the case since I just want a normal SDR sRGB image file at the end of the day, but the JPG looks much more reasonable than the PNG, which looks too bright still. I'd prefer to generate PNGs just to avoid JPG compression.

The command lines are pretty straightforward:
JPG: `texconv -ft jpg -tonemap *.hdr`
PNG: `texconv -ft png -tonemap *.hdr`

I've attached some images.

syntheticChart.01.exr comes from AMPAS ACES Dropbox.
syntheticChart.01.hdr is the EXR converted through some random website.
syntheticChart.01.jpg and syntheticChart.01.png were converted with texconv, and the PNG is brighter than the JPG when I want them to look the same.

[syntheticChart.01.zip](https://github.com/microsoft/DirectXTex/files/8636118/syntheticChart.01.zip)

**Comment by walbourn** [comment]
I'll need to dig into it a bit more, but I suspect the PNG is still getting the default `sRGB` colorspace chunk added to it, while the JPG is not having sRGB set as the colorspace.
