### ISSUE TITLE
Clang Warning Diagnostic: definition of implicit copy assignment operator for 'HDRColorA/INTColor' is deprecated because it has a user-provided copy constructor

### ISSUE THREAD

**Issue by SK83RJOSH** [microsoft/DirectXTex#284]
I ran into this error while compiling my project with with clang using `-Wall -Werror` and wanted to bring it to your attention.

An easy fix would be adding the following pragma to DirectXTexP.h:
```cpp
#pragma clang diagnostic ignored "-Wdeprecated-copy-with-user-provided-copy"
```

Or you can use default for the copy constructors, or remove them entirely, both types are POD so there's no need for a user-defined copy constructor:
```cpp
class HDRColorA
{
    HDRColorA(const HDRColorA& c) noexcept = default;
};

class INTColor
{
    INTColor(const INTColor& c) noexcept = default;
};
```

**Comment by walbourn** [comment]
Thanks for the feedback.

BTW, what version of clang/LLVM are you using?

**Comment by SK83RJOSH** [comment]
> Thanks for the feedback.

No problem! 😄 

> BTW, what version of clang/LLVM are you using?

This was picked up on LLVM-13.0.0, but I tested in godbolt against newer versions [here](https://godbolt.org/z/sjzY4ePhh). It seems that this particular warning isn't always on by default, even with -Wall, but still probably worth fixing just in case. I also encountered a similar warning that pops up occasionally on GCC related to BC6HBC7 encoding. Specifically [`stringop-overflow`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstringop-overflow:~:text=%2DWno%2Dstringop%2Doverflow) complaining about `aEndPts[p]` [here](https://github.com/microsoft/DirectXTex/blob/main/DirectXTex/BC6HBC7.cpp#L3344:35) and [here](https://github.com/microsoft/DirectXTex/blob/main/DirectXTex/BC6HBC7.cpp#L3344:35). Not sure if how to go about disabling that one, though.

Otherwise these were the only errors I ran into, my build suite tests compilation across macOS (using CPU only operations), Ubuntu, and Windows. Probably the only reason I ran into these in the first place. 🙂

**Comment by walbourn** [comment]
Addressed in this commit: 

https://github.com/microsoft/DirectXTex/commit/a189a1952aa6bd0b69a7678ea1b3278cb6a745d3
