### ISSUE TITLE
Replace <malloc.h> with standard <stdlib.h>

### ISSUE THREAD

**Issue by dtzxporter** [microsoft/DirectXTex#285]
Malloc.h is non-standard and won't compile on certain platforms that don't include one.

This will help build the library cross platform :D

**Comment by walbourn** [comment]
malloc is required for the ``_aligned_malloc`` used for _WIN32 platforms. I had it guarded properly in ``scoped.h``, but did not in the ``DirectXTexP.h`` header.

Note I already include <cstdlib> which is the C++ version of ``stdlib.h``.

**Comment by walbourn** [comment]
https://github.com/microsoft/DirectXTex/commit/5a7b9b51ed6cba2f2b9d6888e60625a4034a5e1e
