### ISSUE TITLE
texassemble can not make v-cross layout images properly.

### ISSUE THREAD

**Issue by matyalatte** [microsoft/DirectXTex#288]
Hi, I used texassemble to make cross layout images from cubemaps.
(As an example, I'll use [this cubemap from another git repository](https://github.com/mono/opentk/blob/main/Source/Examples/Data/Textures/earth-cubemap.dds).)

`h-cross` command worked fine for my cubemaps like this.
![Screenshot (770)](https://user-images.githubusercontent.com/69258547/198974536-cab773b6-14d6-4b72-abf0-fbcedd5f373e.png)

But I noticed `v-cross` will put some faces with wrong rotations.
![Screenshot (771)](https://user-images.githubusercontent.com/69258547/198974969-a0b89cc7-a8dc-492d-912c-f99e7b1e23e5.png)

Is it a bug? (I mean, texassemble should use FlipRotate function for v-cross?)
Or there are some dds textures for v-cross layout and others are for h-cross?

**Comment by walbourn** [comment]
I intended to use the layouts as shown [here](https://docs.unity3d.com/uploads/Textures/CubeLayout6Faces1.png).

```
//      posy
// negx posz negx
//      negy
//      negz
```

Instead I ended up using:

```
//      posy
// posz posx negz
//      negy
//      negx
```

I can fix it.

**Comment by matyalatte** [comment]
Thanks for your reply.
So, your plan is to change offsets?
Will you add a way to rotate negz by 180 degrees?
Or any chance I can contribute?

I think there should be an option for negz like this.
```c++
if (index == 5 && dwOptions & (uint64_t(1) << OPT_ROTATE_NEGZ)) {
    std::unique_ptr<ScratchImage> timage(new (std::nothrow) ScratchImage);
    hr = FlipRotate(*img, TEX_FR_ROTATE180, *timage);
    if (FAILED(hr))
    {
        wprintf(L" FAILED Rotating negz image (%08X%ls)\n", static_cast<unsigned int>(hr), GetErrorDesc(hr));
        return 1;
    }
    hr = CopyRectangle(*timage->GetImage(0, 0, 0), rect, *dest, dwFilter | dwFilterOpts, offsetx, offsety);
}
else {
    hr = CopyRectangle(*img, rect, *dest, dwFilter | dwFilterOpts, offsetx, offsety);
}
```

**Comment by walbourn** [comment]
The new ``v-cross-fnz`` command in the attached PR should do what you want:

![t](https://user-images.githubusercontent.com/11866002/199160005-02618a89-2209-4293-ad23-5677562ec482.jpg)

**Comment by matyalatte** [comment]
Thanks for the fix!
Yeah, it worked with my cubemaps.
