### ISSUE TITLE
Green artifact specs in BC6H compressed cubemap

### ISSUE THREAD

**Issue by musicaljelly** [microsoft/DirectXTex#301]
I have a specular environment map generated by IBLBaker that looks fine on visual inspection. Running it through the DirectXTex BC6H GPU compressor leaves behind very bright green specs in seemingly random (but consistent from run-to-run) spots on mip 0 of each cubemap face. The green specs are clusters of ~1-10 pixels, often with RGB values of (0.0, 810.0, 0.0) or (0.0, 35776.0, 0.0) or similar.

Running the same texture through the CPU compressor also produces green specs, but much less bright and noticeable. These green specs tend to be less clustered, and much less bright (green values of ~1.5 rather than in the hundreds or thousands).

[The input image I used](https://www.dropbox.com/s/xw9sy0ie7do0whl/Input.dds?dl=1)
[After GPU BC6H compression](https://www.dropbox.com/s/yrw4iiu5zsmrehf/GPUOutput.dds?dl=1)
[After CPU BC6H compression](https://www.dropbox.com/s/ee74xlf3ddmo30p/CPUOutput.dds?dl=1)

I used the latest (December 2022) texconv.exe to generate the two output cubemaps. The texconv.exe invocations I used are:
`texconv -o <OUTPUT_DIR> -f BC6H_UF16 <INPUT_PATH>`
`texconv -o <OUTPUT_DIR> -f BC6H_UF16 -nogpu <INPUT_PATH>`

Let me know if there's any other information I can provide.

**Comment by walbourn** [comment]
There are a few negative values in the green channel of input.dds. I wonder if that’s the source of the spots?

```
texdiag.exe analyze Input.dds

Result item   0, mip   0:
          Minimum - (0.000000 -0.003662 0.000000 1.000000)
          Average - (0.021466 0.020569 0.098170 1.000000)
          Maximum - (1.359375 1.075195 1.386719 1.000000)
         Variance - (8162.633789 3265.017578 23229.140625 0.000000)
          Std Dev - (90.347298 57.140331 152.411087 0.000000)
        Luminance - 1.149756 (maximum)

Result item   1, mip   0:
          Minimum - (0.000000 -0.002901 0.000000 1.000000)
          Average - (0.012002 0.018630 0.114855 1.000000)
          Maximum - (0.852051 0.887207 1.177734 1.000000)
         Variance - (1565.408447 1668.836792 10315.150391 0.000000)
          Std Dev - (39.565243 40.851398 101.563530 0.000000)
        Luminance - 0.886758 (maximum)

Result item   2, mip   0:
          Minimum - (0.000000 -0.002810 0.000000 1.000000)
          Average - (0.042417 0.027978 0.139926 1.000000)
          Maximum - (1.470703 1.341797 1.494141 1.000000)
         Variance - (21406.115234 6777.263184 37132.726562 0.000000)
          Std Dev - (146.308289 82.324135 192.698532 0.000000)
        Luminance - 1.366963 (maximum)

Result item   3, mip   0:
          Minimum - (0.000000 -0.002098 0.000000 1.000000)
          Average - (0.009151 0.013301 0.073028 1.000000)
          Maximum - (1.246094 1.262695 1.307617 1.000000)
         Variance - (1498.845093 1507.269775 8517.763672 0.000000)
          Std Dev - (38.714920 38.823574 92.291733 0.000000)
        Luminance - 1.260928 (maximum)

Result item   4, mip   0:
          Minimum - (0.000000 -0.004627 0.000000 1.000000)
          Average - (0.032802 0.021726 0.121696 1.000000)
          Maximum - (1.372070 0.937012 1.410156 1.000000)
         Variance - (13478.554688 2206.976807 35565.562500 0.000000)
          Std Dev - (116.097176 46.978470 188.588348 0.000000)
        Luminance - 0.943315 (maximum)

Result item   5, mip   0:
          Minimum - (0.000000 -0.001917 0.000000 1.000000)
          Average - (0.061077 0.060653 0.130210 1.000000)
          Maximum - (1.476562 1.388672 1.496094 1.000000)
         Variance - (46665.878906 32402.958984 56632.378906 0.000000)
          Std Dev - (216.022873 180.008224 237.975586 0.000000)
        Luminance - 1.398447 (maximum)
```

**Comment by musicaljelly** [comment]
Ah good catch, I imagine that's indeed the source of the artifacts. I'll recreate this bug over in the IBLBaker issue tracker, thanks for taking a look.

Out of curiosity, is this something it'd be reasonable for DirectXTex to catch? That is, if I compress to DXGI_FORMAT_BC6H_UF16 but a negative value is encountered, it either flags it as an error or clamps the input value?

**Comment by walbourn** [comment]
It should probably clamp, but I'll need to check.

**Comment by musicaljelly** [comment]
(continuing from Discord)

Related to this issue but not exactly the same: Mipmaps generated with bicubic filtering can result in negative numbers. Which in turn lead to artifacts when compressed as BC6H_UF16.

Based on my (very limited) understanding, this isn't _strictly_ a bug. Bicubic filtering can lead to negative values, as far as I can tell that's a known behaviour of the method (although surprising behaviour to the uninitiated like myself who was blindly picking the highest quality filtering method for offline processing). And compressing negative values using BC6H_UF16 isn't really a valid thing to try and do.

But I would describe all this as _surprising_ behaviour. Assuming I don't know about the underlying details and pitfalls, it feels easy to accidentally end up with artifacts doing what feels like a natural sequence of operations (which is how I stumbled across this behaviour).

I'm curious, does it makes sense to just clamp values going into Compress() when using BC6H_UF16, and call it a day? Or is there more to it?

**Comment by walbourn** [comment]
I *believe* the fix here is in ``BC6HEncode.hlsl`` to change the three instances of ``g_Input.Load`` and make them:

```
shared_temp[GI].pixel = g_Input.Load(uint3(base_x + threadInBlock % 4, base_y + threadInBlock / 4, 0)).rgb;
shared_temp[GI].pixel = max(shared_temp[GI].pixel, float3(0,0,0));
```

Rebuild the whole library and see if that fixes the green artifacts issue

**Comment by musicaljelly** [comment]
Applying that change indeed eliminates the artifacts I was seeing in all cases I've tried. Thanks so much for taking a look!
