### ISSUE TITLE
Will ScratchImage be really zero'd by Initialize*() functions?

### ISSUE THREAD

**Issue by matyalatte** [microsoft/DirectXTex#302]
Hi, I'm using texassemble codes as a dll function to convert cubemaps to cross images.
And I noticed sometimes the initialize functions gave colored images.
(It'll only happen when I use the dll functions many times in a process. So it won't happen on the official texassemble, I think.)

Here is a sample image that was saved before copying cubemap faces.
It looks like the buffers for other images.
![Initialize2D](https://user-images.githubusercontent.com/69258547/211395921-aa2837ad-b6ba-4273-80a2-273c685a0107.png)

When I used memset for m_memory, the issue seemed to be resolved.
But [the wiki page](https://github.com/microsoft/DirectXTex/wiki/Image) says they'll be zero'd by the initialize functions.

**Comment by walbourn** [comment]
I must have misread my code there. I'm zeroing the image metadata, but not the memory :(  I should fix that.
