### ISSUE TITLE
DDSTextureLoader12 copy queue D3D12 ERROR: GPU-BASED VALIDATION

### ISSUE THREAD

**Issue by howprice** [microsoft/DirectXTex#306]
I am using the resource created by DirectX::LoadDDSTextureFromFile with a custom resource uploader which uses the copy queue. This results in the following error: 

```
D3D12 MESSAGE: GPU-BASED VALIDATION: TRACE BEGIN: Frame 0::ResourceUploader [ EXECUTION MESSAGE #1014: BEGIN_EVENT]
D3D12 ERROR: GPU-BASED VALIDATION: CopyTextureRegion, Incompatible resource state: Dest state invalid, Resource: 0x00000255A379D700:'textures/lion_basecolor.dds', Subresource Index: [0], Resource State: D3D12_RESOURCE_STATE_COPY_DEST(0x400, For GRAPHICS or COMPUTE command list), Required State Bits: D3D12_RESOURCE_STATE_COPY_DEST(0x400, For COPY command list), Draw Count [0], Dispatch Count [0], Command List: 0x00000255A38BF010:'ResourceUploaderCopyCommandList', Resources used in COPY command lists must start out in the D3D12_RESOURCE_STATE_COMMON state.  This includes Resources created in a COPY_SOURCE or COPY_DEST state.  [ EXECUTION ERROR #942: GPU_BASED_VALIDATION_INCOMPATIBLE_RESOURCE_STATE]
```

My workaround is to modify CreateTextureResource to change the InitialResourceState passed to CreateCommittedResource from D3D12_RESOURCE_STATE_COPY_DEST to D3D12_RESOURCE_STATE_COMMON.

I have considered adding this as a param to the functions in the stack (LoadDDSTextureFromFile, LoadDDSTextureFromFileEx, CreateTextureFromDDS and CreateTextureResource) to allow DDSTextureLoader12 to be compatible with custom uploaders, whether they choose to use graphics or copy command lists. Is there a better solution?

Thanks

**Comment by walbourn** [comment]
That error doesn't make a lot of sense, but I'll take a look.

Note that for the Xbox platform, COMMON state promotion and decay are *opt-in* which is why I don't use it.

**Comment by walbourn** [comment]
Note that the text of the message here is a little confusing, but has been cleaned up for the next version of Windows and I believe in the current Agilty SDK.

**Comment by howprice** [comment]
Thanks

**Comment by walbourn** [comment]
I've enabled GPU-based validation on my system, but I'm not seeing any warnings for this scenario. What build of the OS are you using? Are you using the Agility SDK?

**Comment by howprice** [comment]
Hi Chuck. Thanks for trying to repro this. 

Windows 10 Version 22H2 (OS Build 19045.2486)
Not using Agility SDK
NVIDIA 3070 Driver version: 527.56

**Comment by walbourn** [comment]
On my Windows 11 22H2 system, using NVidia I'm getting:

```
D3D12 WARNING: ID3D12Device::CreateCommittedResource: Ignoring InitialState D3D12_RESOURCE_STATE_COPY_DEST. Buffers are effectively created in state D3D12_RESOURCE_STATE_COMMON. [ STATE_CREATION WARNING #1328: CREATERESOURCE_STATE_IGNORED]
```

**Comment by howprice** [comment]
I can confirm that using Agility SDK (1.608.2) resolves this issue. The application now runs with vanilla DDSTextureLoader12.cpp. Many thanks.
