### ISSUE TITLE
bindings for rust?

### ISSUE THREAD

**Issue by Detector-I** [microsoft/DirectXTex#313]
Hi, is there any plan to create some sort of binding for rust?
Currently there is near to nothing crates to work with Texture formats in rust (and those that are already available like `Image` crate are very limiting and can't even load some of DXT formats).
having this library could help so many people.

**Comment by Ryan-rsm-McKenzie** [comment]
I've written Rust bindings for this library available here: https://crates.io/crates/directxtex  
It doesn't cover the entire API, but it does get most of it.
