### ISSUE TITLE
Using heap allocated ScratchImage on CopyRectangle

### ISSUE THREAD

**Issue by YouKnow-sys** [microsoft/DirectXTex#314]
Hi, basically what I want to do is opening a DDS file and doing some stuff on it, but the thing is I need to first make sure that it isn't compressed, so what I need to do is check If it's compressed and if yes first decompress it and then continue working on it.
But the problem is I'm not sure how to reassign the new created decompressed ScratchImage to top level one so I can continue using it
Here is an example
```c++
ScratchImage image;
// ... Load something in it
if (IsCompress(...))
{
    ScratchImage new_image;
    // ... Decompress
    image = new_image; // this won't work because the = overload is on delete...
}
```
I tried to create the `image` on heap using `new` and it did mostly worked, except for some reason it didn't worked on `CopyRectangle`...
So what should I do in this case?
Sorry if here isn't the right place to ask.

**Comment by walbourn** [comment]
For examples of this kind of operation, see [texconv](https://github.com/microsoft/DirectXTex/blob/main/Texconv/texconv.cpp) around line 2205+.

**Comment by YouKnow-sys** [comment]
thank you, this lead me to the right way.
