### ISSUE TITLE
sRGB to linear color space conversion not working

### ISSUE THREAD

**Issue by W4RH4WK** [microsoft/DirectXTex#324]
If I understand texconv's commandline flags correctly, one should be able to convert an input image from sRGB color space to linear color space by using `-srgbi` and a format without the `_SRGB` suffix.

However, this does not seem to work for me.

```
texconv.exe -y -srgbi -f BC7_UNORM assets/models/Default_albedo.jpg

texdiag.exe info assets/models/Default_albedo.dds
Microsoft (R) DirectX Texture Diagnostic Tool [DirectXTex] Version 2023.1.31.1
Copyright (C) Microsoft Corp.

assets/models/Default_albedo.dds
        width = 2048
       height = 2048
        depth = 1
    mipLevels = 12
    arraySize = 1
       format = BC7_UNORM
    dimension = 2D
   alpha mode = Unknown
       images = 12
   pixel size = 5461 (KB)
```

Viewing the resulting DDS texture in a texture viewer, or in-engine shows the texture to be too bright.
I've also tried `R8G8B8A8_UNORM` as format, but the result does not change.

If I use `BC7_UNORM_SRGB` or `R8G8B8A8_UNORM_SRGB` as target format the texture looks normal in the viewer and in-engine.

texconv Version 2023.1.31.1

Texture Viewer:

![image](https://user-images.githubusercontent.com/328798/219967665-2118a12e-77ca-46f3-8935-5bf98cd35fd7.png)

In-Engine:

![image](https://user-images.githubusercontent.com/328798/219967674-26e954c1-19d9-4899-921c-8b9271c0adf1.png)

Source Image:

![Default_albedo](https://user-images.githubusercontent.com/328798/219967694-f43a4bcf-d355-4f82-90ae-35a4605f2b2e.jpg)

**Comment by walbourn** [comment]
Looks like there's a bug in the GPU compress handling here for this case.
