### ISSUE TITLE
texconv fails to strip the file path when using forward slash

### ISSUE THREAD

**Issue by ratchetfreak** [microsoft/DirectXTex#332]
when using forward slash delimited file paths (like one might in wine) the output path doesn't strip the portion before the last forwardslash

leading to the error message: 

> writing /run/user/1000/.tmpjW8EGr\Z:/home/r/Garbage/Marble023_1K-JPG/Marble023_1K_Color.dds FAILED: Path not found.

The relevant code is around https://github.com/microsoft/DirectXTex/blob/main/Texconv/texconv.cpp#L3571-L3575

Only the backwards slash is checked, the forward slash it treated as part of the file/directory name.

**Comment by walbourn** [comment]
Should I sanitize input to convert any use of `\` to `/` or do I need to support a mode where I use `/` instead of `\`?
