### ISSUE TITLE
Add DXGI_FORMAT_BC1_UNORM = 71 support 

### ISSUE THREAD

**Issue by Raiwulf** [microsoft/DirectXTex#346]
Hi,

 Please add support for this format. Thank you so much for the hardwork <3.

**Comment by walbourn** [comment]
This format is already supported. What operation are you trying to perform?

**Comment by Raiwulf** [comment]
I was trying to bulk cut(quality,size decrease) .dds files with this format. I found a wrapper on github thinking it's not supported yet. I will look again. Thank you
