### ISSUE TITLE
Add TEX_FILTER_RGB_COPY_ALPHA

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXTex#347]
DirectXTex filter flags includes:

```
TEX_FILTER_RGB_COPY_RED = 0x1000,
TEX_FILTER_RGB_COPY_GREEN = 0x2000,
TEX_FILTER_RGB_COPY_BLUE = 0x4000,
```

The request here is to add a ``TEX_FILTER_RGB_COPY_ALPHA = 0x8000``.

For RGBA -> R, this would indicate copying the source A channel to R instead of the monochrome or R, G, or B channels.

This would also apply to !Depth -> Depth.

This flag could also be used to add A to the mix for RGBA -> RG conversions.

* RED | GREEN (the default)
* RED | BLUE
* GREEN | BLUE
* RED | GREEN

would add:

* RED | ALPHA
* GREEN | ALPHA
* BLUE | ALPHA

> The new flag would be ignored when doing any RGB conversions where the source has no alpha channel.

**Comment by Detector-I** [comment]
Hi, is there any update to this new feature?

**Comment by walbourn** [comment]
@Detector-I  - See the PR for the proposed implementation.
