### ISSUE TITLE
Implement PNG and JPEG file I/O for Linux

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXTex#351]
For non-Win32 platforms like Linux and Windows Subsystem for Linux, WIC is not supported. This currently means support for reading/writing formats is limited to DDS, TGA, and HDR which are implemented without using WIC. OpenEXR also works when using the 3rd party library.

For Linux, I could provide 'adapters' similar to the DirectXEXR.h/.cpp files for using **libpng** and **libjpeg** directly without WIC.

**Comment by luncliff** [comment]
Hi, @walbourn . Appreciate your work on the project.

I'd like to contribute to this issue, but have no idea about the testing of implementation.
Should I open a draft and then request some help for it?

**Comment by luncliff** [comment]
Forgot to link this issue with the PR 🤣
