### ISSUE TITLE
Broken output from texdiag.exe

### ISSUE THREAD

**Issue by jessey-git** [microsoft/DirectXTex#353]
Seems like there might be an issue with `texdiag.exe` somehow writing out bad strings?
```
.\texdiag.exe info .\wind_28.dds
Microsoft (R) DirectX Texture Diagnostic Tool [DirectXTex] Version 2023.4.28.1
Copyright (C) Microsoft Corp.

)\wind_28.dds FAILED (80004005: Unspecified error
^                                                ^^^
```

You can use the attached file for example. By most  accounts the file is broken, but that's fine. The bug here is with the tool output.
[wind_28.zip](https://github.com/microsoft/DirectXTex/files/11491196/wind_28.zip)

**Comment by walbourn** [comment]
The problem with this file is that it has an ill-formed header.

The file begins with the correct 'magic value' for the DDS file, but it has a header with a reported size of 24, not 124 bytes.

```
    struct DDS_HEADER
    {
        uint32_t        size; // This should be 124. It's 24 in your file.
        uint32_t        flags;
        uint32_t        height;
        uint32_t        width;
        uint32_t        pitchOrLinearSize;
        uint32_t        depth; // only if DDS_HEADER_FLAGS_VOLUME is set in flags
        uint32_t        mipMapCount;
        uint32_t        reserved1[11];
        DDS_PIXELFORMAT ddspf;
        uint32_t        caps;
        uint32_t        caps2;
        uint32_t        caps3;
        uint32_t        caps4;
        uint32_t        reserved2;
    };
```

What created this file?

**Comment by jessey-git** [comment]
@walbourn The file initially came into Blender's bug tracker and the user said "I don't know what program created the problematic file. I downloaded it from the Internet.".

But again, the main issue for this bug is the tool output. I know the file is broken. But the tool's output shouldn't also be broken, err... it looks broken right?

**Comment by walbourn** [comment]
I see. I'm looking at that.
