### ISSUE TITLE
question RXGB dtx5 support?

### ISSUE THREAD

**Issue by y2keeth** [microsoft/DirectXTex#358]
if so what settings are for that format ?

**Comment by y2keeth** [comment]
never mind just read no other formats are supported

**Comment by walbourn** [comment]
if I understand correctly, you'd like built-in support for creating the "DXT5n/RXGB" variant for normals maps as described [here](https://www.gamedev.net/forums/topic/593576-dxt-normal-map-formats-and-the-new-nvidia-texture-tools/).

Essentially it's just the BC3 compression scheme with the channels swizzled a bit.

**Comment by walbourn** [comment]
Quick follow-up: Why not just use BC5 which is supported by all Direct3D Hardware Feature Level 10.0 or better hardware?

**Comment by y2keeth** [comment]
> BC5

I know bc3 will work for quake4 not sure about bc5

**Comment by y2keeth** [comment]
> DXT5nm/RXGB

DXT5nm/RXGB would this work for diffuse maps also?

**Comment by y2keeth** [comment]
"The RXGB formal on the other hand, is a DXT5 image with x in the alpha channel, the red channel empty, and the original green and blue channels left in tact. This improves the compression quality for the x component and doesn't require any reconstruction."
is what i am looking for

**Comment by y2keeth** [comment]
tried bc 5 didnt work
 BC3 compression scheme with the channels swizzled to RXGB would be perfect i think

**Comment by walbourn** [comment]
What do you mean by "didn't work"? I'm guessing the shader in question is not reconstructing the third channel?

**Comment by y2keeth** [comment]
> What do you mean by "didn't work"? I'm guessing the shader in question is not reconstructing the third channel?

bc5 would not load in quake 4

**Comment by walbourn** [comment]
It appears from some old toolsets that this is specific to Doom 3 and requires a special FourCC value 'R', 'X', 'G', 'B'.

**Comment by walbourn** [comment]
I've added support for both reading and writing RXGB, but by default it will write RXGB as 'DXT5' legacy format for general usage when using ``-f RXGB``. If you want to force the use of "RXGA'", you will use ``-f RXGA -dx9``.

This also adds support for ``-f DXT5nm``.

**Comment by y2keeth** [comment]
great thanks a lot

**Comment by y2keeth** [comment]
another question  this gui for Texconv
https://vvvv.org/contribution/texconvgui#comment-280714
has a iminium compression setting is that a option for rxbg? without the gui of course.

**Comment by y2keeth** [comment]
"q: Uses minimal compression"- will this work with rxgb?

**Comment by walbourn** [comment]
The options `-bc x (max) and -bc q (quick)` apply to BC7 compression where it influences the mode choices evaluated for each block. It has no impact on BC3/DXT5 compression.

If you need a 'real-time' solution for BC3 compression, you should look at [this sample](https://github.com/microsoft/Xbox-GDK-Samples/tree/main/Samples/Graphics/FastBlockCompress) which has a SIMD implementation of a Fast Block Compress scheme.

**Comment by y2keeth** [comment]
thought  minimal compression might have been a way to do that bummer it only works on bc7

**Comment by y2keeth** [comment]
should add minimal compression for everything

**Comment by walbourn** [comment]
I guess "minimal compression" for BC1-BC5 could be a form of Fast Block Compress, although the sample only has SSE/SSE2 intrinsics implementations and not ARM intrinsics, so that's a bit of work that would need done. Also, the quality of this is *really* poor, so it doesn't really make a lot of sense to do it for an offline compression tool. Minimal for BC6H/BC7 CPU compression make sense as that algorithm is a LOT slower.

For "maximal compression" for BC1-BC5, this would require some new algorithm implementation. DirectXTex uses the original D3DX9 compression algorithm. There were some experiments with using alternative algorithms, but none of them did much to improve quality.

The BC1-BC3 improvement I am consideration adding here is the 'optimal solid color block' algorithm used in *squish*. See https://github.com/microsoft/DirectXTex/issues/223. This doesn't apply to BC4/BC5 since those don't use color encoding at all, just alpha.

**Comment by y2keeth** [comment]
> I guess "minimal compression" for BC1-BC5 could be a form of Fast Block Compress, although the sample only has SSE/SSE2 intrinsics implementations and not ARM intrinsics, so that's a bit of work that would need done. Also, the quality of this is _really_ poor, so it doesn't really make a lot of sense to do it for an offline compression tool. I had this idea in it's own issue and decided it made more sense as a sample than a library feature. #18
> 
> > Minimal for BC7 CPU compression just tries mode 6. It doesn't try any other modes. This is generally a bit better than BC1-BC3, but it's error-rate is a lot higher than other modes. This doesn't do anything for BC6H compression.
> 
> For "maximal compression" for BC1-BC5, this would require some new algorithm implementation. DirectXTex uses the original D3DX9 compression algorithm. There were some experiments with using alternative algorithms, but none of them did much to improve quality.
> 
> > Maximum compression for BC7 CPU just means it tries mode 0 & 2 which are slower to evaluate. Otherwise it just skips those and only considers 1, 3, 4, 5, 6, or 7. This doesn't do anything for BC6H compression.
> 
> The BC1-BC3 improvement I am consideration adding here is the 'optimal solid color block' algorithm used in _libsquish_ and _NVTT_. See #223. This doesn't apply to BC4/BC5 since those don't use color encoding at all, just alpha.

ok just thought it was a good suggestion, guess not
