### ISSUE TITLE
A tga with all 0 alpha channels, when converted to dds in dxt5 format, the alpha channels become all 255

### ISSUE THREAD

**Issue by sky-force** [microsoft/DirectXTex#359]
Hello, I have a problem today, I used a tga with all 0 alpha channel, when I convert to dds in dxt5 format, the alpha channel becomes all 255. I dont know why and how can I get the correct alpha channel? 
Thanks.

Here are the conversion commands I use:
texconv.exe -nologo -y -gpu 0 -if TRIANGLE_DITHER -f "DXT5" -o "." "./test.tga"

![image](https://github.com/microsoft/DirectXTex/assets/22298575/436e91db-8a2c-4c2a-ae41-140224bc2c12)
![image](https://github.com/microsoft/DirectXTex/assets/22298575/d4e1a035-664a-4c32-9d80-b2b8e11131b4)

**Comment by walbourn** [comment]
Note you can disable this behavior via the ``TGA_FLAGS_ALLOW_ALL_ZERO_ALPHA`` flag, but I don't have this flag exposed in texconv at the moment.

**Comment by sky-force** [comment]
> There are some legacy TGA files that indicate they have an alpha channel, but it is all zeroes. This results in an invisible image since '0' means fully transparent so the color is never used in 'normal' situations. Therefore the TGA reader checks to see if the Alpha channel is all zero, and if it is it sets it to fully opaque.
> 
> What is your scenario where you want a fully 0 alpha channel?

Thanks for your response.
We have some old shaders that rely on this case.

**Comment by walbourn** [comment]
So you need a switch added to ``texconv`` for setting the ``TGA_FLAGS_ALLOW_ALL_ZERO_ALPHA`` flag.

**Comment by sky-force** [comment]
> So you need a switch added to `texconv` for setting the `TGA_FLAGS_ALLOW_ALL_ZERO_ALPHA` flag.

Wow, thank you very much.
