### ISSUE TITLE
Provide a way for callers to get the legacy DDS format information

### ISSUE THREAD

**Issue by 0xC0000054** [microsoft/DirectXTex#372]
This is important for various advanced scenarios that deal with the legacy DDS formats.

For example, when reading the "swizzled" BC3 variants the caller could use that information to reorder the image channels.

My Paint.NET DDS plugin could use it to automatically select the correct DDS format when the user saves the file, or warn the user if the format is not supported.
I have had multiple reports from users who edit DDS textures without knowing what format they need to select when saving.
Currently the only thing I can do is tell them to get the original format using `texdiag`.

**Comment by walbourn** [comment]
Would optionally returning a ``DDS_PIXELFORMAT`` be sufficient? For modern DXGI formats, it would be returning a FourCC of "DX10".

```
    struct DDS_PIXELFORMAT
    {
        uint32_t    size;
        uint32_t    flags;
        uint32_t    fourCC;
        uint32_t    RGBBitCount;
        uint32_t    RBitMask;
        uint32_t    GBitMask;
        uint32_t    BBitMask;
        uint32_t    ABitMask;
    };
```

**Comment by 0xC0000054** [comment]
> Would optionally returning a DDS_PIXELFORMAT be sufficient?

Yes, that would work.

**Comment by walbourn** [comment]
@0xC0000054 This work shipped in the [September 2023 release](https://github.com/microsoft/DirectXTex/releases/tag/sept2023).
