### ISSUE TITLE
Progress reporting for compression and format conversion

### ISSUE THREAD

**Issue by 0xC0000054** [microsoft/DirectXTex#374]
I implemented this in the DirectXTex fork that my Paint.NET DDS plugin uses, and I was wondering if there is any interest in adding it to the main DirectXTex distribution.
My implementation is a bit of a hack, so I am not sure how much of it could be reused.

The progress callback is defined as `bool ProgressCallback(size_t done, size_t total)`.
If the callback returns `false`, DirectXTex returns `HRESULT_FROM_WIN32(ERROR_CANCELLED)`.

I am not sure of the proposed `CompressEx` and `ConvertEx` methods should add the progress callback as a parameter, or use an options structure to simplify future expansion.
The existing `Compress` and `Convert` would call the Ex methods with the progress callback set to `nullptr`.

This should probably also be added to the `Decompress` method for consistency, but my current implementation does not have that.

**Comment by walbourn** [comment]
Generally the BC formats decompress very quickly, so there's no need for a progress callback.

**Comment by 0xC0000054** [comment]
> Generally the BC formats decompress very quickly, so there's no need for a progress callback.

That make sense.
