### ISSUE TITLE
BC3(no GPU) Compress texture colors  towards green

### ISSUE THREAD

**Issue by lblliu** [microsoft/DirectXTex#377]
compress:
format=DXGI_FORMAT_BC3_UNORM_SRGB,
compress=TEX_COMPRESS_PARALLEL,
threshold=TEX_THRESHOLD_DEFAULT,
The texture color compressed using this parameter is incorrect, and green will be accentuated
How to solve this problem

**Comment by lblliu** [comment]
grey becomes greenish after conversion

**Comment by walbourn** [comment]
BC1, BC2, and BC3 all use 5:6:5 RGB values for the color endpoints, so they share the same behavior that many conversions to 5:6:5 RGB color do which is a tendency to accentuate green.

The default encoding uses a luminance weighting, so you can try using ``BC_FLAGS_UNIFORM`` as well.
