### ISSUE TITLE
Decoding the swizzled BC3 formats

### ISSUE THREAD

**Issue by 0xC0000054** [microsoft/DirectXTex#379]
PR #362 mentions that the texconv `-swizzle` command can be used after reading the swizzled BC3 formats.

What  `-swizzle` command string would be needed to convert a RXGB image to RGBA?

I tried using `RXGB`, but I am not sure if that output is correct.

**Comment by walbourn** [comment]
So a 'no change' swizzle is `-swizzle rgba` meaning nothing is moved.  In a RXGB encoded image, the red and alpha are swapped. Use ``-swizzle agbr``.

**Comment by 0xC0000054** [comment]
Thanks.

I found descriptions for the other swizzled RGB formats in the Compressonator source code: https://github.com/GPUOpen-Tools/compressonator/blob/0bea29d5ab01c688c8408edf50a8f13dfe7a915b/cmp_compressonatorlib/common/commontypes.h#L130C17-L130C17
I was not able to find anything on the `A2D5` format.
