### ISSUE TITLE
DDS files with a DDS_PIXELFORMAT size of 24

### ISSUE THREAD

**Issue by 0xC0000054** [microsoft/DirectXTex#392]
I encountered these files as part of a [bug report](https://forums.getpaint.net/topic/122998-cant-open-certain-dds-files-in-newer-version-but-can-in-3511/) on my Paint.NET DDS plugin.
The files are associated with mods for the Steam game Flat Out 2, all files use the legacy DX 9 header with DXT1-DXT5.

Whatever tool produced these files correctly sets the DDS header size, but for some reason it sets the `DDS_PIXELFORMAT` size to 24 instead of 32.

[ddspf_24.zip](https://github.com/microsoft/DirectXTex/files/12551254/ddspf_24.zip)

**Comment by walbourn** [comment]
The number of ways people have messed up DDS details over the years is amazing :)

That said, if you look at the definition of the ``DDPIXELFORMAT`` struct, I can actually see the case where you could argue '24' is still value (i.e. some of the unions only have two members). It's weird and I've not seen it before, but it isn't quite as "wrong" as my first impression of it.

```
typedef struct _DDPIXELFORMAT {
  DWORD dwSize;
  DWORD dwFlags;
  DWORD dwFourCC;
  union {
    DWORD dwRGBBitCount;
    DWORD dwYUVBitCount;
    DWORD dwZBufferBitDepth;
    DWORD dwAlphaBitDepth;
  };
  union {
    DWORD dwRBitMask;
    DWORD dwYBitMask;
  };
  union {
    DWORD dwGBitMask;
    DWORD dwUBitMask;
  };
  union {
    DWORD dwBBitMask;
    DWORD dwVBitMask;
  };
  union {
    DWORD dwRGBAlphaBitMask;
    DWORD dwYUVAlphaBitMask;
    DWORD dwRGBZBitMask;
    DWORD dwYUVZBitMask;
  };
} DDPIXELFORMAT, *LPDDPIXELFORMAT;
```

**Comment by 0xC0000054** [comment]
>  I don't know where the hell 24 came from.

I do not know how they got that value either. The only thing I can think of is that they may have assumed that only the unused fields are included in the size.

I already have a fix in my fork, should I submit it as a PR?

**Comment by walbourn** [comment]
Feel free to submit a PR. Accepting 0, 24, or 32 as 'valid'

**Comment by walbourn** [comment]
I wonder how many other variants there are... I don't want to skip validating the value entirely though for security reasons.

**Comment by walbourn** [comment]
Something like the following including an extra check in the "DX10"extension header case since these weird variants only make sense for DX9 legacy files.

```
        if (pHeader->ddspf.size != 0 /* Known variant */
            && pHeader->ddspf.size != 24 /* Known variant */
            && pHeader->ddspf.size != sizeof(DDS_PIXELFORMAT))
        {
            return E_FAIL;
        }

        metadata.mipLevels = pHeader->mipMapCount;
        if (metadata.mipLevels == 0)
            metadata.mipLevels = 1;

        // Check for DX10 extension
        if ((pHeader->ddspf.flags & DDS_FOURCC)
            && (MAKEFOURCC('D', 'X', '1', '0') == pHeader->ddspf.fourCC))
        {
            if (pHeader->ddspf.size != sizeof(DDS_PIXELFORMAT))
            {
                return E_FAIL;
            }

            // Buffer must be big enough for both headers and magic value
            if (size < (sizeof(DDS_HEADER) + sizeof(uint32_t) + sizeof(DDS_HEADER_DXT10)))
            {
                return E_FAIL;
            }
```

**Comment by 0xC0000054** [comment]
> I wonder how many other variants there are... I don't want to skip validating the value entirely though for security reasons.

The most common error I have seen is DDS files that specify one too many mipmaps in the header.

DirectXTex correctly rejects these files as invalid, but it would be nice to have an option to allow those files to be loaded.
Currently, I have to instruct users to re-save those files using a different program that does not validate the mipmap count when loading the file.
I had looked at adding that to my fork, but I could never determine how to implement that change.

**Comment by walbourn** [comment]
Is it always an off-by-one thing?

**Comment by 0xC0000054** [comment]
> Is it always an off-by-one thing?

Yes.

**Comment by walbourn** [comment]
Can you attach an example or two?

**Comment by 0xC0000054** [comment]
The following file is from [this](https://github.com/0xC0000054/pdn-ddsfiletype-plus/issues/14) issue in the pdn-ddsfiletype-plus repository. It is a 256x256 pixel image that specifies 10 mipmaps instead of 9.
The OP said that they found a few other files with the same off-by-one issue.

[beam_lo.zip](https://github.com/microsoft/DirectXTex/files/12572657/beam_lo.zip)

Here is another 256x256 pixel file with 10 mipmaps that I created: [mip-off-by-1.zip](https://github.com/microsoft/DirectXTex/files/12572712/mip-off-by-1.zip)

I also think I may be overestimating the prevalence of this bug, as I often forget that `dwMipCount` includes the main image.

**Comment by 0xC0000054** [comment]
Yes, that is fine.
