### ISSUE TITLE
Cubemap to and from cross 

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXTex#40]
Tool to convert between cross layout images and cubemaps.
- h-strip (height, width *6): posz, posx, negz, negx, posy, negy
- h-strip-xyz (height, width \* 6): pox, negx, posy, negy, posz, negz
- h-cross (height \* 3, width \* 4): negx, posz, posx, negz, posy, negy
- h-cross-flip
- v-cross (height \* 4, width \* 3): negx, posz, posx, posy, negy, negz
- v-cross-flip

**Comment by walbourn** [comment]
considering adding this as an option to ``texassemble``

**Comment by walbourn** [comment]
``texassemble`` now supports h-strip, v-strip, h-cross, and v-cross generation.

**Comment by lanyizi** [comment]
> `texassemble` now supports h-strip, v-strip, h-cross, and v-cross generation.

Looks like `texassemble` only supports creating cross _from cubemap_, not converting h-cross _to cubemap_?

**Comment by walbourn** [comment]
Correct.  I'm guessing that's a feature request :)

**Comment by matyalatte** [comment]
Hi, I implemented this feature for my tools.
So, I think I can contribute to the official branch like this.
https://github.com/matyalatte/DirectXTex/commit/d085c1d1dca649abd4e39368cb7d15c564c6004c
Can I send PR after adding commands for other layouts?
Or is anyone already working on it?

**Comment by walbourn** [comment]
You are welcome to submit a PR. I have a side-project to work on a ``texenvmap`` tool for generating spherical cubemaps, panoramic cubemaps, parabolic cubemaps, but this is a fine addition to ``texassemble``.

**Comment by walbourn** [comment]
You'll need to sync with my main branch for my recent additions of **h-tee** and **v-cross-fzh**.

**Comment by matyalatte** [comment]
Thanks for the comments.
I sent the PR (https://github.com/microsoft/DirectXTex/pull/290).
