### ISSUE TITLE
Texconv.exe can not handle whitespaces in output path

### ISSUE THREAD

**Issue by ErikSteiner** [microsoft/DirectXTex#401]
With the latest release [sept2023](https://github.com/microsoft/DirectXTex/releases/tag/sept2023), I am unable to process the file. Texconv.exe, Version: 2023.9.6.1
```
"C:\Modding\DynDOLOD\Edit Scripts\Texconv.exe" -nologo -gpu 0 -y -sepalpha -aw 256 -m 1 -f BC7_UNORM -bc q -o "C:\Modding\DynDOLOD\TexGen_Output\textures\terrain\lodgen\tfos large juniper trees in the reach sse.esp" -flist "C:\Modding\DynDOLOD\Texconv_18_1_40CF7396A5094054AE8460335AA8BCE4.txt"
reading C:\Modding\DynDOLOD\TexGen_Output\textures\terrain\lodgen\tfos FAILED (80070002: File not found. )
```
Content of `Texconv_18_1_40CF7396A5094054AE8460335AA8BCE4.txt`:
```
C:\Modding\DynDOLOD\TexGen_Output\textures\terrain\lodgen\tfos large juniper trees in the reach sse.esp\k747largejuniper03_00000804.dds
```
The utility tries to use the path `C:\Modding\DynDOLOD\TexGen_Output\textures\terrain\lodgen\tfos` instead of `C:\Modding\DynDOLOD\TexGen_Output\textures\terrain\lodgen\tfos large juniper trees in the reach sse.esp`.

**Comment by walbourn** [comment]
Let me check the filelist processing to see how it handles spaces in filenames...

**Comment by walbourn** [comment]
Did you build a new ``texconv.exe`` with the changes?

**Comment by Azperin** [comment]
No, didn't check release date, thought this important bug is fixed in latest releases

**Comment by walbourn** [comment]
I'll be doing a formal release in the next week.
