### ISSUE TITLE
Does DirectXTex directly depend on ZLIB?

### ISSUE THREAD

**Issue by JPeterMugaas** [microsoft/DirectXTex#426]
I ask because Auxiliary
/DirectXTexEXR.cpp line 25: states

`// Requires the OpenEXR library <http://www.openexr.com/> and ZLIB <http://www.zlib.net>`

but the only mention in CMakeLists.txt is line 352 that adds it to the pkg-config file.  I do not see anything such as:

`find_package(ZLIB)`

If DirectXTex directly requires ZLib, then that DirectXKub;s CNajeKusts should link the library with ZLIB  with something like `target_link_libraries(${PROJECT_NAME} ZLIB::ZLIB)` after finding the ZLIB package.  

If this library does not directly require ZLIB,, CMakeLists.txt should NOT add ZLIB as a dependency in the pkg-config file and the comment I mentioned needs to be fixed and ZLIB should NOT be listed as required in its pkg-config file in this library.

I will look at this further later today.

**Comment by walbourn** [comment]
ZLIB is a dependency of OpenEXR.

**Comment by JPeterMugaas** [comment]
We are talking about an indirect dependency, NOT a direct dependency.  It seems to me that zlib should be removed from the removed from the requires field in the pkg-config file for this package.  If OpenEXR depends upon ZLIB, then that should have been listed in its OpenEXR.pc file.
