### ISSUE TITLE
Can't compile ddsdump

### ISSUE THREAD

**Issue by Rast1234** [microsoft/DirectXTex#430]
I found `ddsdump` utility in wiki: https://raw.githubusercontent.com/wiki/Microsoft/DirectXTex/ddsdump.cpp

However, placing it into source folder and trying to compile gives an error:

`unexpected end of file while looking for precompiled header. Did you forget to add '#include "DirectXTexP.h"' to your source?`

If i do what it suggests, `#include "DirectXTexP.h"`, i get a lot of errors about undeclared identifiers. If i move this include above `ddraw.h` i get only 1 error: 

`syntax error: identifier 'LPRGNDATA'`

I tried to check out nov2018 release which is close to [this thread](https://github.com/Microsoft/DirectXTex/issues/116#issuecomment-414016601) where `ddsdump` was mentioned but had the same errors.

How does one compile `ddsdump`? I understand it's not officially supported because it's not included in the sources. Any hint or a working sample would be cool. Or maybe it will compile only at specific revision?

**Comment by Rast1234** [comment]
I managed to compile it by replacing source of one of the tools, eg `Tools/texdiag/texdiag.cpp` with ddsdump source

**Comment by walbourn** [comment]
It's stand alone. It only needs dds.h.
