### ISSUE TITLE
Does DirectX support direct reading of compressed textures?

### ISSUE THREAD

**Issue by study-it-cause-game** [microsoft/DirectXTex#442]
Is it possible to load BC3 data directly in a streaming manner without using DDS?

**Comment by walbourn** [comment]
I'm not sure what you are asking. There is only one 'defined' format for serializing BC3 data to disk i.e. the DDS or DDS with DX10 header extension.

Direct3D itself doesn't care where the data comes from and never uses DDS header structures. It just expects a block of BC3 data to be present for the texture.
