### ISSUE TITLE
Issue with BC4 Compression + OptimizeAlpha

### ISSUE THREAD

**Issue by DawnlessSky** [Microsoft/DirectXTex#45]
there seems to be an issue with OptimizeAlpha in relation to BC4 compression.  The result is completely wrong.

Before : https://drive.google.com/file/d/0BzuqIF07GjT8NjZMQWpfZU1DelE/view?usp=sharing
After : https://drive.google.com/file/d/0BzuqIF07GjT8TXp1QkhRSEZVQzA/view?usp=sharing

This is a simple test of a BC4 decompressed as RGBA 32 then recompressed to BC4.
In the 2nd texel, the first block's end points are 84, 0.  However, the BC4 compression outputs 84, 255.  This seems to be where the problem starts since the only two available values in the texel are either 0 or 84.  

This changes the color block size.  It will now put twice "1f" in the palette (once as one of the endpoints and once for palette[7])

I think the problem starts in FindEndPointsBC4U.
bUsing4BlockCodec should be renamed to bUsing3BlockCodec and the following "if" reversed.
if (bUsing3BlockCodec) -> OptimizeAlpha for 6 gradients
else -> OptimizeAlpha for 8 gradients

I did modify this in my own code and the result, though still a bit amiss is much improved.

Thanks for looking into it.

**Comment by DawnlessSky** [comment]
Follow up : some troubles were on my end (I was writing back the indice field even though it's the data field that hold the incices... fml)

However, I did have to adjust a few things.  I noticed that when decompressing the original texture, 99% of the blocks were coded with 8 values even if a lot of them had "0" as an endpoint.  I changed to condition for bUsing4BlockCodec to only include 1f.  I also adjusted other little things but I don't think they would matter much for you and this issue.  It now works perfectly!  I hope this was useful to you.

Cheers!

**Comment by walbourn** [comment]
Can you provide a code snippet of the minimal changes to address your concern?

**Comment by DawnlessSky** [comment]
Sorry, had a little trouble with formatting on here.  This was easier : 
https://docs.google.com/document/d/1QsBMxPyZj9_lzJrnpqvJKkXbFfhw9CznZXGU2CePiG0/edit?usp=sharing

This is the code I use in my app (translated to C#)
Changes (other than pure C# translations) are highligthed.

I tested it with the texture provided above and none of the pixels have a difference of more than one shade of red with their original value as a byte (I.E. original : 87 red, new value = 86)

I also tested by enlarging the texture by 200% and re-importing to simulate changes and the import worked perfectly as well.

**Comment by walbourn** [comment]
In the C++ code, the bug I see for BC4 is that in ``FindEndPointsBC4U``, the ``iStart``, ``iEnd`` variables should be ``uint8_t`` and not ``int8_t``.

The name ``bUsing4BlockCodec`` is a little confusing. It refers to the "4 interpolated color values"  rather than the "6 interpolated color values" as described in [Block Compression](https://msdn.microsoft.com/en-us/library/bb694531(v=vs.85).aspx#BC4)  on MSDN.

**Comment by walbourn** [comment]
I'm unable to repro your original issue with the ``texconv`` release from December 2016. The RGBA32 -> BC4U compression looks correct to me even with the code "as is". Did you get the repro originally using your C# code?
