### ISSUE TITLE
keep getting acess denied

### ISSUE THREAD

**Issue by KRASK52** [microsoft/DirectXTex#487]
I am not sure if this is the correct way to seek help for this. I am trying to convert some png to dds and i keep getting this error. I have tried running cmd as admin I have tried running textconv as admin I have tried running them both as admin. I have turned my user account control settings down, I white listed it with windows defender and I set full control to everyone in my files security. I have no idea what i am doing wrong.

Microsoft Windows [Version 10.0.19045.4651]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Dagaroth>texconv -ft dds -f BC1_UNORM -dx10 C:\Users\Dagaroth\textures
Microsoft (R) DirectX Texture Converter [DirectXTex] Version 2024.6.5.1
Copyright (C) Microsoft Corp.

reading C:\Users\Dagaroth\textures FAILED (80070005: Access is denied. )

C:\Users\Dagaroth>

**Comment by walbourn** [comment]
`C:\Users\Dagaroth\textures` points to a directory, not a file.

Try `C:\Users\Dagaroth\textures\*.*` and you might consider adding `-r`

**Comment by walbourn** [comment]
https://github.com/microsoft/DirectXTex/wiki/Texconv

**Comment by KRASK52** [comment]
that did it thank you!
