### ISSUE TITLE
Expose EncodeDDSHeader from DirectXTexXboxDDS.cpp

### ISSUE THREAD

**Issue by helviett** [microsoft/DirectXTex#496]
Right now the only way to save XDDS using DirectXTex library is this:
```cpp
... // image processing, compressing, tiling, etc.
Blob out;
Xbox::SaveToDDSMemory(tiled_image, out);
write_to_file(game_asset_bundle, out.GetBufferPointer(), out.GetBufferSize());
```
This additional copy can be avoided if `EncodeDDSHeader` used inside `Xbox::SaveToDDSMemory` is exposed:
```cpp
uint8_t dds_header[XBOX_HEADER_SIZE];
Xbox::EncodeDDSHeader(tiled_image, dds_header, XBOX_HEADER_SIZE);
write_to_file(game_asset_bundle, dds_header, XBOX_HEADER_SIZE);
write_to_file(game_asset_bundle, tiled_image.GetPointer(), tiled_image.GetSize();
```

**Comment by walbourn** [comment]
Does ``Xbox::SaveToDDSFile`` not work for your scenario?

**Comment by walbourn** [comment]
You want the Xbox version of https://github.com/microsoft/DirectXTex/issues/249

**Comment by helviett** [comment]
> Does `Xbox::SaveToDDSFile` not work for your scenario?

No, I have already opened file that contains multiple textures.

> You want the Xbox version of https://github.com/microsoft/DirectXTex/issues/249
Yes, would be nice to make `EncodeDDSHeader`, `XBOX_HEADER_SIZE`, `DDS_XBOX_HEADER` public. Almost every engine I saw just have to copy these structures into their sources.

**Comment by walbourn** [comment]
The Xbox 'extension' is specific to my Auxiliary library, but I can look at moving the Xbox structs to ``dds.h``.
