### ISSUE TITLE
BC1 srgb to BC1

### ISSUE THREAD

**Issue by revcarl** [Microsoft/DirectXTex#52]
Hi I don't have a lot of experience with textures but I am doing my best to figure it out. I hope you can bear with me, I will try to give as much detail as I can. I am actually using this tool for modding purposes and it is great. What I am trying to do is convert a BC1 4bpp (sRGB DX10+) dds image to a BC1 4bpp (Linear) dds image. I am doing this because photoshop seems to be the only program that can open the first dds file and I just don't have the money for it. I am able to convert the image and have it work on paint.net but when I convert it back the image is lighter than it originally was. It is making me think that some of the dds files information is being lost in the process that you can't get back. Is this the case or is there a different reason for this happening?
Thank You for any help,  RevCarl

PS this is what I am using to convert them: 
`texconv -f BC1_UNORM -srgbi -if LINEAR "C:\Users\kyle\Downloads\Arkham knight\Mods\resorep\retrieved textures\*.dds"`
Then Back:
`texconv -f BC1_UNORM_SRGB -srgbo -if LINEAR -bcdither "C:\Users\kyle\Downloads\Arkham knight\Mods\resorep\retrieved textures\Black and grey\DXGI_FORMAT_BC1_UNORM_SRGB\new\*.dds"`

**Comment by walbourn** [comment]
If the original source image is encoded as ``DXGI_FORMAT_BC1_UNORM_SRGB``, then the first line converted it to a ``DXGI_FORMAT_BC1_UNORM`` (which can be encoded with a legacy DDS header) after converting the content to a non-sRGB (i.e. linear) form. The ``-srgbi`` is redundant if the original format was explictily an sRGB ``DXGI_FORMAT``.

If you wanted to do the original version without modifying the color-space, then you'd use:

    texconv -f BC1_UNORM -srgbo "C:\Users\kyle\Downloads\Arkham knight\Mods\resorep\retrieved textures\*.dds" 

For the second line, if your input source is a ``DXGI_FORMAT_BC1_UNORM``, then by specifying ``BC1_UNORM_SRGB`` it would perform a color-space conversion. The ``-srgbo`` again is redundant becuase the output is an explicitly sRGB ``DXGI_FORMAT``. If you want to avoid a color-conversion, you'd use ``-srgbi``.
> ``-if LINEAR`` isn't relevant as that's for resizing the image or generating mipmaps.

**Comment by revcarl** [comment]
Thank You :) I just tried it and it and what you said worked like a charm. I am going to try it in the game when I get time. If it works it should make a lot of people happy.
