### ISSUE TITLE
Normal map averaging

### ISSUE THREAD

**Issue by dtzxporter** [microsoft/DirectXTex#53]
Would you be interested a feature to calculate the blue channel of a normal map (Given R/G (X/Y))? It was included in the old NVidia tools and would make a great addition to the library, I'd be willing to write the code for this if you'd be willing to merge! Some flag like -navg or something...

**Comment by walbourn** [comment]
Can you explain the use-case for the feature a bit? The old ``D3DX`` function had a number of features which are in the DirectXTex version by combining ``CNMAP_CHANNEL_*`` flags. The code is already set up to use the first ``0xf`` mask of the ``CNMAP_FLAGS`` to select the height-computation mode, so it should b easy enough to add another case.

**Comment by dtzxporter** [comment]
Basically if someone had a previously lets say BC5 encoded image and wanted to decode and use it in Blender per say, it's easier on the user to plugin a normal map with a precalculated blue channel instead of adding the calculation into the material itself.  So it would be useful when transcoding between various 2 channel compressions. It would also be useful to get this working on the GPU as well for the added performance.

**Comment by dtzxporter** [comment]
Yes that was the idea.

**Comment by walbourn** [comment]
Another way to achieve this would be to add special logic to ``Decompress`` so that if the target format has a blue channel it reconstructs it. Of course, that's probably the same as just having it always do that and the B channel would be saved or not depending on the output format.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/DirectXTex/commit/93aa3c6c094394e170cf5bec16c51fbdca722b3b). Keep in mind you still need to ensure the output *has* a blue channel (such as with ``-f R8G8B8A8_UNORM``.
