### ISSUE TITLE
texconv.exe instantly closes itself on launch

### ISSUE THREAD

**Issue by kuro1uta** [microsoft/DirectXTex#537]
Am I supposed to install something before using texconv.exe or something is broken on my end?

**Comment by walbourn** [comment]
The only requirement is you have the Visual Studio REDIST installed. Perhaps you don't have that?

https://aka.ms/vs/17/release/vc_redist.x64.exe

or

https://aka.ms/vs/17/release/vc_redist.arm64.exe

**Comment by kuro1uta** [comment]
I did have it and just tried reinstalling it, still closes itself

**Comment by walbourn** [comment]
To be clear, texconv doesn't have any UI or window associated with it. It's a command-line tool you use from the Command Prompt.
