### ISSUE TITLE
'void*' to 'uint8_t*'

### ISSUE THREAD

**Issue by karurung** [microsoft/DirectXTex#539]
Here is my changed #527 :
https://github.com/microsoft/DirectXTex/pull/527/files

I tried to open an issue for this project.
void* --> uint8_t*

**Comment by karurung** [comment]
@walbourn Hi, I received your message. 
Did I do correctly?
I'm not very familiar with GitHub, so if I didn’t do it correctly, I’ll ask my professor for help. Thank you!

**Comment by karurung** [comment]
I think mine can't re-opened it, so I tried to re-make it.
Here is the link:
https://github.com/microsoft/DirectXTex/pull/540

**Comment by walbourn** [comment]
Fixed.
