### ISSUE TITLE
The term 'texdiag' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by EbiDesa** [microsoft/DirectXTex#547]
i want to check full detail of some DDS Files. but when i use this command: texdiag info dds-source\*.dds > output.txt
powershell says: texdiag :

The term 'texdiag' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ texdiag info dds-source\*.dds > output.txt
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (texdiag:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command texdiag was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\texdiag". See "get-help about_Command_Precedence" for more details.

**Comment by walbourn** [comment]
Did you try making sure you changed to the directory where you downloaded the ``texdiag.exe`` and tried using `.\texdiag`
