### ISSUE TITLE
DDS cube map that DirectXTex corrupts faces when extracting

### ISSUE THREAD

**Issue by 0xC0000054** [microsoft/DirectXTex#560]
The following DDS image has the 2nd through 6th cube map faces corrupted when trying to extract it.

https://github.com/vsg-dev/vsgExamples/blob/master/data/textures/skybox.dds

DirectXTex output (horizontal cross):

![Image](https://github.com/user-attachments/assets/da3aa28a-8b06-4533-97cd-6b1c910e634a)

DDSView renders the image correctly:

![Image](https://github.com/user-attachments/assets/5ed6d6c3-a0a7-4654-9d50-2575e22c1532)

The API call I am using to extract the top-level faces is:
```cpp
const DirectX::Image* face = image.GetImage(0, i, 0);
```

**Comment by walbourn** [comment]
Thank you for the report and repro. It also loads correctly in Visual Studio which uses DirectXTex. I'll look into it.

**Comment by walbourn** [comment]
DDS Dump output for this file:

```
(size: 124) Flags 0002100f: CAPS HEIGHT WIDTH PITCH PIXELFORMAT MIPMAPCOUNT
512 x 512
Pitch: 2048
Mipmap count: 10
Surface flags: 00401008: COMPLEX TEXTURE MIPMAP
Cubemap flags: 0000fe00: CUBEMAP POSX POSY POSZ NEGX NEGY NEGZ
PIXELFORMAT (size 32): 00000004: FOURCC
FourCC = 808540228 'DX10'
dxgiFormat = 28: DXGI_FORMAT_R8G8B8A8_UNORM
resourceDim = 3: DDS_DIMENSION_TEXTURE2D
miscFlag = 00000004: TEXTURECUBE
arraySize = 1
```

**Comment by walbourn** [comment]
Well, `texassemble`'s hcross operation works fine.

![Image](https://github.com/user-attachments/assets/2d04d5ce-f622-466f-8472-beaff879110f)

**Comment by 0xC0000054** [comment]
> What are you doing with each face->rowPitch and face->pixels value to produce your corrupted image?

Calling `DirectXTex::SaveToWICFile`. My test application is: https://github.com/0xC0000054/DumpDdsCubeMapFaces/blob/main/DumpDdsCubeMapFaces.cpp

The bug was initially reported in my Paint.NET plugin, it treats `face->rowPitch` as the stride and `face->pixels` as a pointer to the start of the first row (scan0).

**Comment by 0xC0000054** [comment]
I discovered the source of the bug, it is the presence of the `DirectX::DDS_FLAGS_IGNORE_MIPS` flag. It appears that the presence of that flag is causing DirectXTex to read the wrong image data when loading a cube map with mipmaps.

I can remove that flag as a workaround. but ideally the `DirectX::DDS_FLAGS_IGNORE_MIPS` flag behavior woth multiple images should be fixed.

**Comment by walbourn** [comment]
Thanks! yes, I see that `ignoremips` doesn't work as you might expect for an array or volume texture.

**Comment by walbourn** [comment]
The purpose of `ignoremips` is a simple header hack for some malformed files. I'm making it so that flag is ignored for all arrays/cubemaps.
