### ISSUE TITLE
Using CreateWICTextureFromMemory() or CreateWICTextureFromMemoryEx() with PNG loaded in memory

### ISSUE THREAD

**Issue by Kabak** [Microsoft/DirectXTex#57]
ID3D11Resource** texture always created in DXGI_FORMAT_B8G8R8A8_UNORM pixel format.

How to force create resource in DXGI_FORMAT_R8G8B8A8_UNORM pixel format ?

**Comment by walbourn** [comment]
The WIC codec for PNG is returning the data as BGR, so it maps to ``DXGI_FORMAT_B8G8R8A8_UNORM``. See [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ee719797(v=vs.85).aspx#png__native_codec) for the WIC pixel formats supported by the WIC PNG codec.

If you want a different format, you should use ``Convert`` after loading the image before creating it the texture.

Of course, the question is (A) why does it matter if it's BGR or RGB, and (B) do you really need to use the DirectXTex library to load your DDS or would you be better served by the light-weight [WICTextureLoader](https://github.com/Microsoft/DirectXTK/wiki/WICTextureLoader) module?

**Comment by Kabak** [comment]
A ) I experementing with DirectX 11. SwapChain and all stuff  in my project are in DXGI_FORMAT_R8G8B8A8_UNORM. So, when i use CopySubresourceRegion() i get debugger error about different formats, and i found that PNG textures was created in DXGI_FORMAT_B8G8R8A8_UNORM. 

B ) I prefere to use WICTextureLoader module and CreateWICTextureFromMemoryEx() function
I just add into WIC_LOADER_FLAGS enum new value 

```
    enum WIC_LOADER_FLAGS
    {
        WIC_LOADER_DEFAULT      = 0,
        WIC_LOADER_FORCE_SRGB   = 0x1,
        WIC_LOADER_IGNORE_SRGB  = 0x2,
	WIC_LOADER_FORCE_R8G8B8A8_UNORM	= 0x4,
    };
```
and modify CreateTextureFromWIC() function at line 491 WICTextureLoader.cpp  like that :        ` if (FAILED(hr) || !(support & D3D11_FORMAT_SUPPORT_TEXTURE2D) || (loadFlags & WIC_LOADER_FORCE_R8G8B8A8_UNORM ) )`

thats work for me.
Thanks

**Comment by walbourn** [comment]
Trying to do all your drawing with the copy engine on the hardware is probably the most efficient use of the silicon.  A much better solution is to actually render your textures on the render target, which is much more powerful and flexible. If you are mostly concerned with 2D rendering, take a look at [SpriteBatch](https://github.com/Microsoft/DirectXTK/wiki/Getting-Started) in the _DirectX Tool Kit_.
