### ISSUE TITLE
Resizing a DDS texture with colour RGB data in alpha channel where alpha is zero results in RGB being 0.

### ISSUE THREAD

**Issue by comeradealexi** [Microsoft/DirectXTex#59]
Not sure if there is a setting I'm missing but if I don't resize the texture, the RGB data remains valid.

We've got a 2048x2048 DXT5 DDS texture which we want to half the size of, so using TexConv, we run with the command -w 1024 -h 1024 -m 11. The output texture has no RGB values where the alpha is zero. If I don't specify the texture be resized, the RGB data remains.

I've tried specifying -alpha and -pmalpha but nothing changes.

Thanks!

**Comment by comeradealexi** [comment]
Actually, I believe this is related to https://github.com/Microsoft/DirectXTex/issues/27 

Unsure how to do the same as suggested from the command line however.

**Comment by walbourn** [comment]
Use ``-sepalpha``

**Comment by comeradealexi** [comment]
Thanks @walbourn ! That's fixed the problem.

I think it would be good to add this to the help message for the tool.

Many thanks.

Alex

**Comment by walbourn** [comment]
It's in the output, but the details are covered in the [wiki](https://github.com/Microsoft/DirectXTex/wiki/Texconv).
