### ISSUE TITLE
saving DXGI_FORMAT_BC3_UNORM_SRGB textures

### ISSUE THREAD

**Issue by maartenvd** [Microsoft/DirectXTex#60]
Hi all, I have a ID3D11ShaderResourceView with format DXGI_FORMAT_BC3_UNORM_SRGB. I want to dump this resource to a texture file. Dumping this to dds works perfectly fine : 
```
DirectX::ScratchImage image;
HRESULT hr = CaptureTexture(device, context, pResource, image);
SaveToDDSFile(image.GetImages(), image.GetImageCount(), image.GetMetadata(), DirectX::DDS_FLAGS_NONE, dumpPath);
```

However, these dds files are often not readable in other programs, so ideally I'd like to obtain a different format. I tried the following : 
`hr = DirectX::SaveToWICFile(image.GetImages()[0], DirectX::WIC_FLAGS_NONE,	DirectX::GetWICCodec(DirectX::WIC_CODEC_PNG), dumpPath);`

And this fails with error code 0x7FF8FFCE
When the DXGIFORMAT is something different, like DXGI_FORMAT_R8G8B8A8_UNORM  then the code works perfectly fine. I'm on 64 bit windows 10.

**Comment by maartenvd** [comment]
It may be useful to note that dumping to dds and then using texconv (which uses directxtex afaik) to convert them to pngs works like a charm.

Are there some restrictions on the resources you can pass to capturetexture? Do the textures have to be created with cpu read access? Is there some way I can obtain more useful information? Maybe WIC is the problem?

**Comment by walbourn** [comment]
The only file image format that supports DirectX Block Compressed formats is ``DDS``. The ``DXGI_FORMAT_BC3_UNORM_SRGB`` format can't be fully expressed using the legacy DDS header, so it is written using the DX10 extension header--see [this post](https://blogs.msdn.microsoft.com/chuckw/2010/02/05/the-dds-file-format-lives/) for details.

If you want to write a resource with the format ``DXGI_FORMAT_BC3_UNORM_SRGB`` to a 'legacy' DDS file, you can override the format and set it to ````DXGI_FORMAT_BC3_UNORM``. Or you can use ``Decompress``, ``Convert``, and ``Compress`` to do an sRGB to non-sRGB colorspace conversion.

If you want to write a resource with the format ``DXGI_FORMAT_BC3_UNORM_SRGB`` to a standard file format like ``PNG``, then you should call ``Decompress`` first.
