### ISSUE TITLE
DirectXTex_Windows10.vcxproj gives error MSB4057 when compiling on latest VS2017 (15.4.1)

### ISSUE THREAD

**Issue by 13thsymphony** [Microsoft/DirectXTex#62]
RS3 RTM (16299.15)

Cloned on 10/20/2017. I get the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4057	The target "MarkupCompilePass1" does not exist in the project.	DirectXTex	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets	821	

Haven't gotten to try on a previous version of VS, but assuming that it worked before. I've filed feedback on VS as well.

My VS config is as follows:

Microsoft Visual Studio Enterprise 2017 
Version 15.4.1
VisualStudio.15.Release/15.4.1+27004.2005
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual Basic 2017   00369-60000-00001-AA060
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA060
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA060
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.9.00809.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

TypeScript   2.3.5.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27004.2002
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by walbourn** [comment]
As covered in the [wiki](https://github.com/Microsoft/DirectXTex/wiki/DirectXTex#adding-to-a-vs-solution), you need to install the Windows 10 SDK (14393) or you change the _minimum supported OS_ setting in the ``DirectXTex_Windows10.vcxproj`` to 15063 or 16299.

> This is due to some quirks of the Visual Studio and Windows 10 SDK tooling. The project doesn't make use of XAML, and the _minimum supported OS_ setting is just metadata that has no impact on which Windows 10 SDK is used to build the code.
