### ISSUE TITLE
Strange behavior of SaveWICTextureToFile

### ISSUE THREAD

**Issue by syntaxerror147** [Microsoft/DirectXTex#64]
I'm facing a strange problem. Saving the content of the back buffer works perfectly fine with SaveWICTextureToFile(). I do not render to the back buffer directly however, but to annother texture that supports multisampling. Then I resolve this texture to the backbuffer. If I try to save the former texture, it fails (no error but saves a rectangle with the right dimensions and a random color). Saving the backbuffer works. Even creating annother texture with a D3D11_TEXTURE2D_DESC obtained by the swapchains buffer won't help. It's not an option for me to save the backbuffers content, because I want to save an image with a different resolution.

**Comment by walbourn** [comment]
The ``SaveWICTextureToFile`` function is the [ScreenGrab](https://github.com/Microsoft/DirectXTK/wiki/ScreenGrab) module which is specifically designed for the needs of 'screenshots'. That means it has code to do the ``Resolve`` as part of the capture if you give it an MSAA texture. 

Do you get any output with the Debug device active? I suspect something is causing the resolve to fail...

**Comment by syntaxerror147** [comment]
I'm sorry, the error occurred, because i discarded my view to the texture before saving. So there is no problem with ScreenGrab, respectively SaveWICTextureToFile().
