### ISSUE TITLE
Is the DxTex function "Open onto Alpha Channel Of This Surface" available in texassemble/texconv?

### ISSUE THREAD

**Issue by ChrisWhatever1980** [Microsoft/DirectXTex#66]
In the old DirectX Texture Tool it was possible to load an image directly into the alpha channel of a surface:
![dxtex](https://user-images.githubusercontent.com/9367513/33368874-27a13fa0-d4f3-11e7-92a5-cc12b8987e40.png)

is there a way to achieve the same in the commandline tools texassemble or texconv?

**Comment by walbourn** [comment]
It would be easy enough to implement. I think the main question is what are the exact semantics. I assume it converts an RGB image to monochrome as part of this process but it could also make sense to have a selection from a specific channel.

I think a ``merge`` command for [texassemble](https://github.com/Microsoft/DirectXTex/wiki/texassemble) would be the most useful solution here, one that can pull channels from a set of images and merge them into a single image. I'll take a look.

**Comment by walbourn** [comment]
Note that the legacy dxtex tool would always load the Blue channel of the input image into the Alpha channel of the target.

**Comment by walbourn** [comment]
added the texassemble merge command in [this commit](https://github.com/Microsoft/DirectXTex/commit/b29d024dfc4a73f74fc4dc31b50a7153585e6f03)
