### ISSUE TITLE
Incorrect bit packing in GPU-encoded BC7

### ISSUE THREAD

**Issue by elasota** [Microsoft/DirectXTex#67]
https://github.com/Microsoft/DirectXTex/blob/master/DirectXTex/Shaders/BC7Encode.hlsl

In block_package1, when fixup index is 6:

    block.w = (get_color_index(15) << 29) | (get_color_index(14) << 26) | (get_color_index(13) << 23) |
    (get_color_index(12) << 20) | (get_color_index(11) << 17) | (get_color_index(10) << 14) |
    (get_color_index(9) << 11) | (get_color_index(8) << 8) |
    (get_color_index(7) << 6) | (get_color_index(6) << 4) | get_color_index(5);

Indexes 6 and 7 are shifted 1 bit higher than they should be.  6 and 7 should be 2 bits apart, and all others 3 bits apart, but index 5 is given 4 bits and index 7 is given 2.

**Comment by walbourn** [comment]
Thanks for the report. I'll take a look now that I'm back in the office.

**Comment by walbourn** [comment]
Does this look like the correct fix to you?

    block.w = (get_color_index(15) << 29) | (get_color_index(14) << 26) |  ( get_color_index(13) << 23) |
    (get_color_index(12) << 20) | (get_color_index(11) << 17) | (get_color_index(10) << 14) |
    (get_color_index(9) << 11) | (get_color_index(8) << 8) | 
    (get_color_index(7) << 5) | (get_color_index(6) << 3) | | get_color_index(5);

**Comment by elasota** [comment]
Yeah that looks right.

**Comment by walbourn** [comment]
Do you have a test image that uses this particular codepath you can share?

**Comment by elasota** [comment]
![defect](https://user-images.githubusercontent.com/1137273/34802508-07433df2-f63c-11e7-9f5d-c38861d08958.png)

Encode with texconv -f BC7_UNORM -m 1 -y defect.png

The first byte of the output block (offset 148 in the DDS) is 0xbe, a.k.a. mode 1 partition 47.

The middle 2 pixels in the second row should be the same in the encoded result because they're in the same subset and have the same input value, but they wind up being different because the bits are in the wrong place.

**Comment by walbourn** [comment]
Awesome. Thanks for the specific repro...

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/Microsoft/DirectXTex/commit/1e98b64ab5b2b691010dfeaefb8ceaf38e4813c7)

**Comment by walbourn** [comment]
Fixed in the [February 2018](https://github.com/Microsoft/DirectXTex/releases/tag/feb2018) release
