### ISSUE TITLE
Add a file output switch to texconv

### ISSUE THREAD

**Issue by ceztko** [Microsoft/DirectXTex#69]
Texconv has a `-o` switch to select a different output directory but apparently no way to select a different output file path. This seems an oversight, but it's relevant since it's hard to convert a single DDS input file to other format DDS file. I suggest adding a `-fo` switch (or similar) to handle this use case in easy way. When used in this way, I guess it shouldn't support multiple input files .

**Comment by walbourn** [comment]
The design is lifted from a legacy DirectX SDK Command line tool. So most of the behavior in that way is preserved. if you wanna output adidias into the same folder you're already in you can use the ''-sx'' or ''-px'' to add a prefix or suffix to the output file name.

**Comment by ceztko** [comment]
Sorry, I didn't notice those switches. It's sound weird when ones has the unix command line in mind, but it helps, thank you.

**Comment by chloekek** [comment]
This feature would still be useful to have, in the case where the desired output file basename is not a superstring of the name that texconv would generate and hence -sx and -px would be insufficient. For instance, I wish to convert `Planks023A_1K_Color.jpg` to `planks-albedo.dds`. Currently this requires moving the file after running texconv.

**Comment by fadingsignal** [comment]
I ran into a case where I need the output filename to be different than the input. Nearly all command-line tools support this. Would be very very useful!
