### ISSUE TITLE
Break should be return?

### ISSUE THREAD

**Issue by ramassin** [Microsoft/DirectXTex#70]
https://github.com/Microsoft/DirectXTex/blob/3a4748ddeb143f2592536ca39aba6ed5e68eb5d6/Texdiag/texdiag.cpp#L443

I guess this should be a return istead of a break?
Otherwise the format gets output as , for instance, 
`R32G32B32A32_FLOAT*UNKNOWN*`

**Comment by walbourn** [comment]
Thanks for the report. Fixed in [this commit](https://github.com/Microsoft/DirectXTex/commit/dd85c73fa3fe51da82a80c894cfd50792faee3c6)
