### ISSUE TITLE
Resize() failed with out of memory error sometimes

### ISSUE THREAD

**Issue by talkhelper** [Microsoft/DirectXTex#85]
Hi,
I use DirectxTex lib to capture realtime video clips, I notice sometime I call Resize() to resize images, it failed, and return out of memory error at:
PerformResizeUsingWIC() --- > pWIC->CreateBitmapFromMemory().
I have 8G memory on the Windows 10 system, and I don't know why caused this.
Could you please advise.
Thanks.

Regards,
Jack

**Comment by walbourn** [comment]
Are you building an x64 native application or a 32-bit one?

**Comment by talkhelper** [comment]
It's 32bit application.
Thanks.

**Comment by walbourn** [comment]
Well, then 8 GB of memory on your system is not going to help. A 32-bit application can only allocate about 1.7 GB of physical memory before it fails, and even that is subject to virtual memory address fragmentation issues.

See [Why Your Windows Game Won't Run In 2,147,352,576 Bytes](https://msdnshared.blob.core.windows.net/media/2017/04/Why-Your-Windows-Game-Wont-Run-In-2147352576-Bytes.zip)

**Comment by talkhelper** [comment]
Thanks for the info.
My application doesn't exceed 1 GB memory when the issue occurs, actually I monitor the memory usage all the time, the issue seems to occur under certain resolution of source image, if I change the source window to another size, it works, but for certain size, it failed, and I can't figure out the reason still..
I tried to call CreateBitmapFromMemory once instead of calling it in every resize produce, but it didn't work either..

Is there any alternative solution for resizing, maybe in d3d11 way?
Please advise.
Thanks.

**Comment by walbourn** [comment]
Have you tried using ``TEX_FILTER_FORCE_NON_WIC`` with ``Resize``? I have my own implementation of software filtering that avoids using WIC for certain cases that WIC tends to botch for texture processing.

The other possibility for out-of-memory even when your "working set" is only 1 GB is potentially virtual memory *address* fragmentation, hence the presentation link above.

**Comment by walbourn** [comment]
Any more information on this issue?

**Comment by talkhelper** [comment]
Sorry for the delay response.
I haven't had a time to test the alternative solution yet..
I will report back once I test this.
Thanks for your help.

**Comment by walbourn** [comment]
Any more information here?
