### ISSUE TITLE
Create Nuget package for DirectXTex

### ISSUE THREAD

**Issue by Rashmatash** [Microsoft/DirectXTex#95]
Having a nuget package would make it easier to use this library in other opensource projects.

**Comment by walbourn** [comment]
NuGet package for UWP: [directxtex_uwp](https://www.nuget.org/packages/directxtex_uwp)

NuGet package for Win32 desktop using VS 2015 Update 3 or VS 2017: [directxtex_desktop_2015](https://www.nuget.org/packages/directxtex_desktop_2015)

**Comment by Rashmatash** [comment]
Great! Thank you! Last time I looked there was no nuget yet, hence my question.

**Comment by walbourn** [comment]
I had some requests for both DirectXTex and DirectXMesh which are both being used by the [glTF Toolkit](https://github.com/Microsoft/glTF-Toolkit), so I have NuGets for them now.

**Comment by rivaldo4t** [comment]
Hi, Noob here.

I have installed nugets for DirectXTex, OpenEXR and Zlib in my solution. Is there a guide that'll help me read and write EXR files from my solution. 

Thanks in advance!

**Comment by walbourn** [comment]
See the [wiki](https://github.com/Microsoft/DirectXTex/wiki/Adding-OpenEXR)
