### ISSUE TITLE
Invalid character in DirectXTexConvert.cpp.

### ISSUE THREAD

**Issue by 24kwakahana** [Microsoft/DirectXTex#98]
I used this library in visual studio 2015 for Japanese. The warning of C4819 arrived in DirectXTexConvert.cpp. It looks like used special character as bellow: 

```
// Y?  = Y - 16
// Cb? = Cb - 128
// Cr? = Cr - 128

// R = 1.1644Y? + 1.5960Cr?
// G = 1.1644Y? - 0.3917Cb? - 0.8128Cr?
// B = 1.1644Y? + 2.0172Cb?

```
so please don't use special character in this source.

**Comment by walbourn** [comment]
Thanks. Fixed in [this commit](https://github.com/Microsoft/DirectXTex/commit/8a2847dc4e2c8a0ddc759a278ad78584d20873f3)
